import type { Metadata } from "next";
import { Camera, Quote } from "lucide-react";
import { BasicContentPage } from "../../components/basic-content-page";
import { VideoDepoimentos } from "../../components/video-depoimentos";
export const metadata:Metadata={title:"Depoimentos | Viagem Perfeita Turismo",description:"Relatos reais vinculados ao Instagram oficial da Viagem Perfeita Turismo.",alternates:{canonical:"/depoimentos"}};
const testimonials=[
  {quote:"Foi incrível! Momentos maravilhosos com esta caravana de fé.",name:"Eliana Souza",context:"Caravana em Israel",url:"https://www.instagram.com/viagemperfeitatrip/reel/DCC391rROqj/",image:"/media/official-instagram/israel-caravana-eliana.jpg",alt:"Registro de uma caravana da Viagem Perfeita em Israel"},
  {quote:"Muito top! Vale super a pena.",name:"Kathreina",context:"Experiência em Orvieto, Itália",url:"https://www.instagram.com/viagemperfeitatrip/reel/DH6PnxPRpjH/",image:"/media/official-instagram/orvieto-kathreina.jpg",alt:"Registro da experiência da Viagem Perfeita em Orvieto, Itália"},
  {quote:"Cidade linda. Já quero a próxima viagem.",name:"@eu_vitorramos",context:"Experiência em Orvieto, Itália",url:"https://www.instagram.com/viagemperfeitatrip/reel/DH6PnxPRpjH/",image:"/media/official-instagram/orvieto-kathreina.jpg",alt:"Registro da experiência da Viagem Perfeita em Orvieto, Itália"},
];
export default function Page(){const basePath=process.env.NEXT_PUBLIC_BASE_PATH??"";return <BasicContentPage eyebrow="Depoimentos" title="Depoimentos" description="Relatos públicos e vídeos reais de pessoas que viveram experiências com a Viagem Perfeita Turismo."><div className="testimonial-grid">{testimonials.map(item=><a className="testimonial-card testimonial-card-with-photo" href={item.url} target="_blank" rel="noopener noreferrer" key={`${item.url}-${item.name}`}><img src={`${basePath}${item.image}`} alt={item.alt} loading="lazy" decoding="async"/><span className="testimonial-card-content"><Quote/><blockquote>“{item.quote}”</blockquote><span className="testimonial-card-footer"><span><strong>{item.name}</strong><small>{item.context}</small></span><span className="testimonial-source"><Camera/>Ver no Instagram</span></span></span></a>)}</div><p className="testimonial-disclosure">Relatos confirmados em publicações do perfil oficial. A origem permanece disponível para conferência.</p><VideoDepoimentos/></BasicContentPage>}
