"use client";

import {Fragment,useCallback,useEffect,useMemo,useState,type CSSProperties} from "react";
import {AlertTriangle,CalendarCheck,CheckCircle2,CircleDollarSign,Clock3,Download,Headphones,RefreshCw,TrendingUp,Users} from "lucide-react";
import type {LucideIcon} from "lucide-react";
import {getSupabaseBrowserClient} from "../lib/supabase-client";

type Report={leads:{total:number;converted:number;lost:number;unassigned:number};reservations:{total:number;confirmed:number;revenue:number};finance:{receivable:number;overdue:number;paid:number};operations:{overdue_tasks:number;pending_documents:number;email_failures:number};sources:Array<{source:string;total:number}>;stages:Array<{stage:string;total:number}>};
type Performance={sla:{open_conversations:number;awaiting_team:number;waiting_over_sla:number;unassigned:number;ai_active:number;human_active:number;avg_first_response_minutes:number};consultants:Array<{name:string;total:number;converted:number;lost:number;conversion_rate:number}>;caravans:Array<{name:string;interests:number;reservations:number;confirmed:number;revenue:number}>;loss_reasons:Array<{reason:string;total:number}>;stage_aging:Array<{stage:string;total:number;avg_days:number;stalled:number}>;activity_by_hour:Array<{weekday:number;hour:number;total:number}>};
const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value||0);const dateInput=(date:Date)=>date.toISOString().slice(0,10);

export function AdminReports(){
 const now=useMemo(()=>new Date(),[]),[from,setFrom]=useState(dateInput(new Date(now.getFullYear(),now.getMonth(),1))),[to,setTo]=useState(dateInput(now)),[data,setData]=useState<Report|null>(null),[performance,setPerformance]=useState<Performance|null>(null),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);setMessage("");const client=getSupabaseBrowserClient();if(!client)return;const[summary,center]=await Promise.all([client.rpc("crm_report_summary",{date_from:from,date_to:to}),client.rpc("crm_performance_center",{date_from:from,date_to:to})]);if(summary.error){setMessage("Não foi possível carregar os relatórios com a permissão atual.");setData(null)}else setData(summary.data as Report);setPerformance(center.error?null:center.data as Performance);setLoading(false)},[from,to]);useEffect(()=>{load()},[load]);
 function exportCsv(){if(!data)return;const rows:Array<Array<string|number>>=[["Indicador","Valor"],["Leads",data.leads.total],["Convertidos",data.leads.converted],["Perdidos",data.leads.lost],["Reservas confirmadas",data.reservations.confirmed],["Receita confirmada",data.reservations.revenue],["A receber",data.finance.receivable],["Em atraso",data.finance.overdue],...(performance?.consultants??[]).map(item=>[`Consultor: ${item.name} (${item.conversion_rate}% conversão)`,item.total])];const csv=rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(";")).join("\n");const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([`\ufeff${csv}`],{type:"text/csv;charset=utf-8"}));link.download=`relatorio-vp-${from}-${to}.csv`;link.click();URL.revokeObjectURL(link.href)}
 const conversion=data?.leads.total?Math.round(data.leads.converted/data.leads.total*100):0,reservationRate=data?.leads.total?Math.round(data.reservations.confirmed/data.leads.total*100):0;const metrics:Array<[LucideIcon,string,string|number]>=[[Users,"Leads",data?.leads.total??0],[TrendingUp,"Conversão",`${conversion}%`],[CalendarCheck,"Reservas confirmadas",data?.reservations.confirmed??0],[CheckCircle2,"Conversão em reserva",`${reservationRate}%`],[CircleDollarSign,"Receita confirmada",money(data?.reservations.revenue??0)],[CircleDollarSign,"A receber",money(data?.finance.receivable??0)],[AlertTriangle,"Em atraso",money(data?.finance.overdue??0)],[AlertTriangle,"Tarefas vencidas",data?.operations.overdue_tasks??0]];
 return <><section className="crm-panel crm-report-toolbar"><div><h2>Central de Performance</h2><p>Vendas, atendimento, gargalos e oportunidades em uma visão gerencial.</p></div><div className="crm-report-filters"><label>De<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={load}><RefreshCw/>Atualizar</button><button onClick={exportCsv} disabled={!data}><Download/>Exportar CSV</button></div></section>{message?<div className="crm-alert">{message}</div>:null}{loading?<section className="crm-panel">Carregando indicadores…</section>:data?<><div className="crm-metrics report-metrics">{metrics.map(([Icon,label,value])=><div key={label}><Icon/><span>{label}</span><b>{value}</b></div>)}</div>{performance?<PerformanceCenter data={performance}/>:<div className="crm-alert crm-alert-neutral">Aplique a migration da Central de Performance para visualizar SLA, consultores, caravanas e gargalos.</div>}<div className="crm-report-grid"><ReportBars title="Origem dos leads" items={data.sources.map(item=>({label:item.source,total:item.total}))}/><ReportBars title="Distribuição no funil" items={data.stages.map(item=>({label:item.stage.replaceAll("_"," "),total:item.total}))}/><section className="crm-panel"><h2>Saúde operacional</h2><ul className="crm-health-list"><li><span>Leads sem responsável</span><b>{data.leads.unassigned}</b></li><li><span>Documentos pendentes</span><b>{data.operations.pending_documents}</b></li><li><span>Falhas de e-mail</span><b>{data.operations.email_failures}</b></li><li><span>Pagamentos recebidos</span><b>{money(data.finance.paid)}</b></li></ul></section></div></>:null}</>;
}

function PerformanceCenter({data}:{data:Performance}){const alerts=[data.sla.waiting_over_sla?`${data.sla.waiting_over_sla} conversa(s) ultrapassaram 15 minutos sem atendimento`:"SLA de atendimento sob controle",...data.stage_aging.filter(item=>item.stalled>0).slice(0,2).map(item=>`${item.stalled} oportunidade(s) paradas em ${item.stage}`)];return <><section className="crm-panel sla-panel"><div className="panel-title-row"><div><h2>SLA do WhatsApp</h2><p>Tempo de resposta, distribuição e equilíbrio entre IA e equipe.</p></div><Headphones/></div><div className="sla-strip"><span className={data.sla.waiting_over_sla?"is-critical":""}><AlertTriangle/><small>Fora do SLA</small><b>{data.sla.waiting_over_sla}</b></span><span><Clock3/><small>1ª resposta</small><b>{data.sla.avg_first_response_minutes} min</b></span><span><Headphones/><small>Em aberto</small><b>{data.sla.open_conversations}</b></span><span><Users/><small>Sem responsável</small><b>{data.sla.unassigned}</b></span><span><TrendingUp/><small>IA / Humano</small><b>{data.sla.ai_active} / {data.sla.human_active}</b></span></div><div className="performance-alerts">{alerts.map((alert,index)=><span className={index===0&&data.sla.waiting_over_sla?"critical":""} key={alert}>{alert}</span>)}</div></section><div className="crm-report-grid performance-grid"><PerformanceTable title="Desempenho por consultor" headers={["Consultor","Leads","Convertidos","Conversão"]} rows={data.consultants.map(item=>[item.name,item.total,item.converted,`${item.conversion_rate}%`])}/><PerformanceTable title="Interesse por caravana" headers={["Caravana","Interesses","Reservas","Confirmadas"]} rows={data.caravans.map(item=>[item.name,item.interests,item.reservations,item.confirmed])}/><PerformanceTable title="Tempo e gargalos no funil" headers={["Etapa","Oportunidades","Média","Paradas"]} rows={data.stage_aging.map(item=>[item.stage,item.total,`${item.avg_days} dias`,item.stalled])}/><ReportBars title="Motivos de perda" items={data.loss_reasons.map(item=>({label:item.reason,total:item.total}))}/></div><ActivityHeatmap items={data.activity_by_hour}/></>}
function PerformanceTable({title,headers,rows}:{title:string;headers:string[];rows:Array<Array<string|number>>}){return <section className="crm-panel performance-table"><h2>{title}</h2>{rows.length?<div className="performance-table-scroll"><table><thead><tr>{headers.map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={`${row[0]}-${index}`}>{row.map((value,cell)=><td key={`${index}-${cell}`}>{cell===0?String(value):<b>{value}</b>}</td>)}</tr>)}</tbody></table></div>:<p>Sem dados no período.</p>}</section>}
function ActivityHeatmap({items}:{items:Performance["activity_by_hour"]}){const days=["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"],hours=[8,10,12,14,16,18,20],max=Math.max(1,...items.map(item=>item.total));const total=(day:number,hour:number)=>items.filter(item=>item.weekday===day&&item.hour>=hour&&item.hour<hour+2).reduce((sum,item)=>sum+item.total,0);return <section className="crm-panel heatmap-panel"><h2>Horários de maior procura</h2><p>Mensagens recebidas por dia e faixa de horário para orientar escalas e automações.</p><div className="activity-heatmap"><i/>{hours.map(hour=><b key={hour}>{hour}h</b>)}{days.map((day,dayIndex)=><Fragment key={day}><strong>{day}</strong>{hours.map(hour=>{const value=total(dayIndex+1,hour);return <span key={`${day}-${hour}`} title={`${day}, ${hour}h: ${value} mensagens`} style={{"--heat":String(value/max)} as CSSProperties}>{value||""}</span>})}</Fragment>)}</div></section>}
function ReportBars({title,items}:{title:string;items:Array<{label:string;total:number}>}){const max=Math.max(1,...items.map(item=>item.total));return <section className="crm-panel"><h2>{title}</h2>{items.length?items.map(item=><div className="report-bar" key={item.label}><span>{item.label}</span><i style={{width:`${Math.max(8,item.total/max*100)}%`}}/><b>{item.total}</b></div>):<p>Sem dados no período.</p>}</section>}
