"use client";
import {useCallback,useEffect,useState} from "react";
import {Activity,ArrowRight,BarChart3,CheckCircle2,CircleDot,RefreshCw,Search,ShieldCheck,Sparkles,Target,TrendingUp,Users} from "lucide-react";
import {getSupabaseBrowserClient} from "../lib/supabase-client";

type Center={funnel:{visits:number;leads:number;qualified:number;proposals:number;reservations:number};scores:Array<{tier:string;total:number}>;channels:Array<{source:string;leads:number;conversions:number}>;keywords:Array<{keyword:string;leads:number}>;forecast:{weighted_leads:number;estimated_revenue:number};overdue_sla:number};
type Channel={id:string;name:string;platform:string;simulation_mode:boolean;credentials_configured:boolean;real_activation_approved:boolean};
type Cluster={id:string;name:string;funnel_stage:string;intent:string;keywords:string[];recommended_channel:string;priority:number;status:string};
type Cadence={id:string;name:string;goal:string;trigger_tier:string;simulation_mode:boolean;max_attempts:number};
const empty:Center={funnel:{visits:0,leads:0,qualified:0,proposals:0,reservations:0},scores:[],channels:[],keywords:[],forecast:{weighted_leads:0,estimated_revenue:0},overdue_sla:0};
const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value||0);

export function AdminAcquisition(){
 const[data,setData]=useState<Center>(empty),[channels,setChannels]=useState<Channel[]>([]),[clusters,setClusters]=useState<Cluster[]>([]),[cadences,setCadences]=useState<Cadence[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const s=getSupabaseBrowserClient();if(!s)return;setLoading(true);const[center,c,k,d]=await Promise.all([s.rpc("acquisition_performance_center"),s.from("acquisition_channels").select("id,name,platform,simulation_mode,credentials_configured,real_activation_approved").order("name"),s.from("keyword_clusters").select("id,name,funnel_stage,intent,keywords,recommended_channel,priority,status").order("priority",{ascending:false}),s.from("sales_cadences").select("id,name,goal,trigger_tier,simulation_mode,max_attempts").eq("active",true)]);if(center.error)setMessage("Aplique a migration do Acelerador de Vendas para ativar os indicadores.");else{setData(center.data as Center);setMessage("")}setChannels((c.data??[]) as Channel[]);setClusters((k.data??[]) as Cluster[]);setCadences((d.data??[]) as Cadence[]);setLoading(false)},[]);
 useEffect(()=>{load()},[load]);
 const f=data.funnel,leadConversion=f.leads?Math.round(f.reservations/f.leads*100):0,qualification=f.leads?Math.round(f.qualified/f.leads*100):0;
 return <section className="growth-module">
  <div className="campaign-simulation"><ShieldCheck/><div><b>Captação segura em modo simulação</b><span>SEO, conteúdo e atribuição funcionam sem mídia paga. Google Ads, Meta Ads e disparos somente serão ativados com credenciais, orçamento e aprovação administrativa.</span></div></div>
  <section className="crm-panel growth-heading"><div><small>Acelerador de viagens</small><h2>Funil em Y: atração, qualificação e vendas previsíveis</h2><p>Inbound, parcerias, indicações e atendimento convergem para o mesmo CRM, score e processo comercial.</p></div><button onClick={load}><RefreshCw/>Atualizar</button></section>
  {message?<div className="crm-alert">{message}</div>:null}
  <div className="growth-kpis"><Kpi icon={Users} label="Leads" value={loading?"—":f.leads}/><Kpi icon={Target} label="Qualificados A/B" value={loading?"—":f.qualified}/><Kpi icon={TrendingUp} label="Taxa de qualificação" value={`${qualification}%`}/><Kpi icon={CheckCircle2} label="Reservas" value={f.reservations}/><Kpi icon={CircleDot} label="Conversão" value={`${leadConversion}%`}/><Kpi icon={BarChart3} label="Previsão ponderada" value={money(data.forecast.estimated_revenue)}/></div>
  <div className="growth-funnel crm-panel"><h2>Jornada comercial unificada</h2><div className="growth-y"><div><b>Inbound</b><span>Google · Meta · Conteúdo · Landing pages</span></div><ArrowRight/><div><b>Qualificação</b><span>Score A–D · intenção · perfil · engajamento</span></div><ArrowRight/><div><b>Venda consultiva</b><span>Roteiro · proposta · reserva · pós-venda</span></div><div><b>Relacionamento</b><span>Igrejas · líderes · indicações · atendimento</span></div><ArrowRight/></div><p className={data.overdue_sla?"growth-warning":"growth-ok"}>{data.overdue_sla?`${data.overdue_sla} lead(s) ultrapassaram o SLA comercial.`:"SLA comercial sob controle."}</p></div>
  <div className="growth-grid">
   <section className="crm-panel"><h2>Canais e governança</h2><p>Todos os conectores comerciais começam bloqueados para gasto e envio.</p><div className="growth-list">{channels.map(item=><div key={item.id}><span><b>{item.name}</b><small>{item.platform}</small></span><em className={item.real_activation_approved?"is-live":"is-sim"}>{item.real_activation_approved?"Ativo":"Simulação"}</em></div>)}</div></section>
   <section className="crm-panel"><h2>Distribuição de score</h2><p>Prioridade calculada automaticamente a cada novo interesse.</p><div className="score-bands">{["A","B","C","D"].map(tier=><span key={tier}><b>{tier}</b><strong>{data.scores.find(x=>x.tier===tier)?.total??0}</strong><small>{tier==="A"?"Contato imediato":tier==="B"?"Até 30 min":tier==="C"?"Nutrição":"Educativo"}</small></span>)}</div></section>
   <section className="crm-panel growth-keywords"><h2><Search/> Palavras-chave por intenção</h2><p>Arquitetura própria para SEO, conteúdo e campanhas futuras.</p>{clusters.map(item=><article key={item.id}><header><b>{item.name}</b><span>{item.funnel_stage}</span></header><p>{item.keywords.join(" · ")}</p><small>{item.recommended_channel} · prioridade {item.priority}</small></article>)}</section>
   <section className="crm-panel"><h2><Sparkles/> Cadências comerciais</h2><p>Automação assistida: IA acolhe, o consultor assume e todas as ações ficam auditáveis.</p>{cadences.map(item=><article className="cadence-card" key={item.id}><b>{item.name}</b><span>Score {item.trigger_tier} · até {item.max_attempts} etapas</span><p>{item.goal}</p><small><ShieldCheck/> {item.simulation_mode?"Simulação — sem disparo real":"Ativa"}</small></article>)}</section>
   <section className="crm-panel"><h2><Activity/> Origem e conversão</h2>{data.channels.length?data.channels.map(item=><div className="growth-bar" key={item.source}><span>{item.source}</span><i style={{width:`${Math.max(8,item.leads/Math.max(1,...data.channels.map(x=>x.leads))*100)}%`}}/><b>{item.leads}</b><small>{item.conversions} vendas</small></div>):<p>Os canais aparecerão assim que os próximos leads forem captados com UTM.</p>}</section>
   <section className="crm-panel"><h2>Previsibilidade</h2><div className="forecast-number"><b>{data.forecast.weighted_leads}</b><span>reservas ponderadas no pipeline</span></div><div className="forecast-number"><b>{money(data.forecast.estimated_revenue)}</b><span>receita potencial estimada*</span></div><small>*Projeção gerencial, não garantia de resultado. Usa score do lead e ticket-base configurado.</small></section>
  </div>
 </section>
}
function Kpi({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string|number}){return <article><Icon/><span>{label}</span><b>{value}</b></article>}
