"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AtSign, Bot, Camera, CheckCircle2, Link2, LoaderCircle, MessageCircle, Pause, Play, Plus, ShieldCheck, Sparkles, Users } from "lucide-react";
import { getSupabaseBrowserClient } from "../lib/supabase-client";

type Flow={id:string;name:string;description:string|null;status:"draft"|"active"|"paused"|"archived";trigger_type:string;objective:string|null;created_at:string};
type Channel={status:string;last_error:string|null};
type AutomationRuntime={aiEnabled:boolean;aiMode:string;providerReady:boolean;facebook:string;whatsapp:string};
const templates=[
 {trigger:"instagram_comment",title:"Comentário para conversa",objective:"Transformar comentários em leads qualificados",icon:AtSign,steps:["Responder o comentário","Enviar DM contextual","Perguntar destino e período","Capturar WhatsApp e e-mail","Criar lead e avisar consultor"]},
 {trigger:"instagram_keyword",title:"Palavra-chave no Direct",objective:"Entregar roteiro e iniciar qualificação",icon:Sparkles,steps:["Reconhecer palavra-chave","Confirmar caravana","Entregar informações aprovadas","Capturar dados","Transferir quando houver intenção de compra"]},
 {trigger:"instagram_story_mention",title:"Menção ou resposta ao Story",objective:"Agradecer e abrir conversa comercial",icon:Camera,steps:["Agradecer interação","Identificar interesse","Apresentar opções confirmadas","Criar oportunidade","Continuar com IA ou humano"]},
 {trigger:"instagram_dm",title:"Atendimento automático no Direct",objective:"Responder dúvidas e encaminhar vendas 24 horas",icon:Bot,steps:["Classificar intenção","Consultar base oficial","Responder sem inventar dados","Qualificar lead","Transferir para equipe"]},
];
const labels:Record<string,string>={instagram_comment:"Comentário",instagram_keyword:"Palavra-chave",instagram_story_mention:"Story",instagram_story_reply:"Resposta ao Story",instagram_dm:"Direct",instagram_ad_referral:"Anúncio",instagram_follow:"Novo seguidor"};
// The Instagram Business Login app is a child app of the main Meta app and
// therefore has its own application id and secret.
const INSTAGRAM_APP_ID="934096495646187",INSTAGRAM_REDIRECT_URI="https://viagemperfeita.github.io/TURISMO/admin/configuracoes/";

export function AdminInstagramOAuthCallback(){
 const[notice,setNotice]=useState("");
 useEffect(()=>{const code=new URLSearchParams(window.location.search).get("code");if(!code)return;const client=getSupabaseBrowserClient();if(!client)return;setNotice("Concluindo a conexão segura do Instagram…");client.functions.invoke("instagram-oauth-connect",{body:{code,redirect_uri:INSTAGRAM_REDIRECT_URI}}).then(({data,error})=>{window.history.replaceState({},"",window.location.pathname);setNotice(error||!data?.connected?"A Meta autorizou o acesso, mas a conexão operacional não foi concluída. Tente novamente.":`Instagram @${data.username} conectado com segurança.`)})},[]);
 return notice?<div className="crm-alert" role="status">{notice}</div>:null;
}

export function AdminInstagramAutomation(){
 const[flows,setFlows]=useState<Flow[]>([]),[channel,setChannel]=useState<Channel|null>(null),[runtime,setRuntime]=useState<AutomationRuntime>({aiEnabled:false,aiMode:"desativado",providerReady:false,facebook:"aguardando",whatsapp:"aguardando"}),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[selected,setSelected]=useState(templates[0]),[keywords,setKeywords]=useState("roteiro, israel, caravana, valor"),[name,setName]=useState(templates[0].title);
 const connected=channel?.status==="connected"&&!channel?.last_error;
 const load=useCallback(async()=>{const client=getSupabaseBrowserClient();if(!client)return;const[{data:f},{data:c},{data:ai},{data:social},{data:wa}]=await Promise.all([client.from("automation_flows").select("id,name,description,status,trigger_type,objective,created_at").eq("channel","instagram").order("created_at",{ascending:false}),client.from("channel_accounts").select("status,last_error").eq("channel","instagram").limit(1).maybeSingle(),client.from("ai_configurations").select("enabled,mode,provider_ready").limit(1).maybeSingle(),client.from("channel_accounts").select("channel,status").eq("channel","messenger").limit(1).maybeSingle(),client.from("whatsapp_accounts").select("status").eq("phone_e164","5531995285665").maybeSingle()]);setFlows((f??[]) as Flow[]);setChannel(c as Channel|null);setRuntime({aiEnabled:Boolean(ai?.enabled),aiMode:String(ai?.mode??"desativado"),providerReady:Boolean(ai?.provider_ready),facebook:String(social?.status??"aguardando"),whatsapp:String(wa?.status??"aguardando")})},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{const code=new URLSearchParams(window.location.search).get("code");if(!code)return;const client=getSupabaseBrowserClient();if(!client)return;setBusy(true);setNotice("Concluindo a conexão segura do Instagram…");client.functions.invoke("instagram-oauth-connect",{body:{code,redirect_uri:INSTAGRAM_REDIRECT_URI}}).then(async({data,error})=>{setBusy(false);window.history.replaceState({},"",window.location.pathname);if(error||!data?.connected){setNotice("A Meta autorizou o acesso, mas a conexão operacional não foi concluída. Tente novamente.");return}setNotice(`Instagram @${data.username} conectado com segurança.`);await load()})},[load]);
 const summary=useMemo(()=>({total:flows.length,active:flows.filter(f=>f.status==="active").length,drafts:flows.filter(f=>f.status==="draft").length}),[flows]);
 function choose(template:typeof templates[number]){setSelected(template);setName(template.title)}
 async function create(){const client=getSupabaseBrowserClient();if(!client)return;setBusy(true);setNotice("");const definition={version:1,channel:"instagram",trigger:{type:selected.trigger,keywords:keywords.split(",").map(v=>v.trim().toLocaleLowerCase("pt-BR")).filter(Boolean),match:"contains"},steps:selected.steps.map((label,index)=>({id:`step_${index+1}`,type:index===selected.steps.length-1?"handoff_or_complete":"guided_message",label})),guardrails:{messaging_window_hours:24,require_approved_knowledge:true,never_invent_price:true,human_handoff:true,frequency_limit_per_24h:1}};const{error}=await client.rpc("create_instagram_automation",{flow_name:name,flow_description:selected.objective,flow_trigger:selected.trigger,flow_objective:selected.objective,flow_definition:definition});setBusy(false);if(error){setNotice(`Não foi possível criar: ${error.message}`);return}setNotice("Fluxo criado como rascunho. Revise antes de ativar.");await load()}
 async function change(flow:Flow,status:Flow["status"]){const client=getSupabaseBrowserClient();if(!client)return;setNotice("");const{error}=await client.rpc("set_instagram_automation_status",{flow_id:flow.id,new_status:status});if(error){setNotice(error.message.includes("instagram_not_connected")?"A ativação ficará bloqueada até a Meta liberar e a conta oficial estar conectada.":error.message);return}await load()}
 function connectInstagram(){const url=new URL("https://www.instagram.com/oauth/authorize");url.searchParams.set("enable_fb_login","0");url.searchParams.set("force_authentication","1");url.searchParams.set("client_id",INSTAGRAM_APP_ID);url.searchParams.set("redirect_uri",INSTAGRAM_REDIRECT_URI);url.searchParams.set("response_type","code");url.searchParams.set("scope","instagram_business_basic,instagram_business_manage_messages,instagram_business_manage_comments,instagram_business_content_publish");window.location.assign(url.toString())}
 return <div className="ig-automation">
  <section className="crm-panel"><div className="crm-panel-head"><div><Bot/><h2>Central da automação da IA</h2></div><span><ShieldCheck/> Operação governada</span></div><p>A IA recebe, qualifica e responde apenas nos canais liberados. Consentimento, janela de atendimento, tomada humana e auditoria permanecem obrigatórios.</p><div className="ig-stats"><article><Bot/><strong>{runtime.aiEnabled&&runtime.providerReady?"Pronta":"Protegida"}</strong><span>IA · {runtime.aiMode}</span></article><article><Camera/><strong>{connected?"Conectado":"Pendente"}</strong><span>Instagram</span></article><article><MessageCircle/><strong>{["connected","active","ativo"].includes(runtime.facebook)?"Conectado":"Pendente"}</strong><span>Messenger</span></article><article><Users/><strong>{runtime.whatsapp==="ativo"?"Conectado":"Pendente"}</strong><span>WhatsApp oficial</span></article></div></section>
  <section className="crm-panel ig-hero"><div><span className="ig-kicker"><Camera/> Instagram Automation</span><h2>Transforme conversas em oportunidades</h2><p>Crie jornadas próprias para comentários, Direct e Stories, integradas ao CRM YOAV, à IA e à equipe humana.</p><button type="button" className="crm-primary" onClick={connectInstagram} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Link2/>}{busy?"Conectando…":connected?"Renovar conexão do Instagram":"Conectar Instagram oficial"}</button>{channel?.last_error?<div className="crm-alert" role="alert">A credencial do Instagram precisa ser renovada para voltar a enviar respostas.</div>:null}</div><div className={`ig-connection ${connected?"connected":"pending"}`}><span/><div><strong>{connected?"Instagram conectado":channel?.last_error?"Reconexão necessária":"Aguardando Meta"}</strong><small>{connected?"Eventos e mensagens disponíveis":channel?.last_error?"As entradas continuam no CRM; renove o acesso para responder":"Autorize a conta oficial para ativar"}</small></div></div></section>
  <section className="ig-stats"><article><MessageCircle/><strong>{summary.total}</strong><span>Fluxos</span></article><article><Play/><strong>{summary.active}</strong><span>Ativos</span></article><article><Pause/><strong>{summary.drafts}</strong><span>Rascunhos</span></article><article><Users/><strong>CRM</strong><span>Captura integrada</span></article></section>
  <section className="crm-panel"><div className="crm-panel-head"><div><Sparkles/><h2>Automações rápidas</h2></div><span><ShieldCheck/> Meta-compliant</span></div><p>Escolha um objetivo e personalize. Todos os fluxos começam como rascunho.</p><div className="ig-templates">{templates.map(template=>{const Icon=template.icon;return <button type="button" key={template.trigger} className={selected.trigger===template.trigger?"selected":""} onClick={()=>choose(template)}><Icon/><strong>{template.title}</strong><small>{template.objective}</small></button>})}</div><div className="ig-builder"><div><label>Nome do fluxo<input value={name} onChange={event=>setName(event.target.value)} maxLength={100}/></label><label>Palavras-chave<input value={keywords} onChange={event=>setKeywords(event.target.value)} placeholder="roteiro, israel, valor"/><small>Separe por vírgulas. Aplicadas quando o gatilho aceitar texto.</small></label><button type="button" className="crm-primary" onClick={create} disabled={busy||name.trim().length<3}><Plus/>{busy?"Criando…":"Criar rascunho"}</button></div><ol>{selected.steps.map(step=><li key={step}><CheckCircle2/>{step}</li>)}</ol></div>{notice?<div className="crm-alert" role="status">{notice}</div>:null}</section>
  <section className="crm-panel"><div className="crm-panel-head"><div><Bot/><h2>Fluxos configurados</h2></div><span>{flows.length} registros</span></div><div className="crm-table-wrap"><table><thead><tr><th>Nome</th><th>Gatilho</th><th>Objetivo</th><th>Status</th><th>Ação</th></tr></thead><tbody>{flows.map(flow=><tr key={flow.id}><td><strong>{flow.name}</strong></td><td>{labels[flow.trigger_type]??flow.trigger_type}</td><td>{flow.objective??"—"}</td><td><span className={`ig-status ${flow.status}`}>{flow.status}</span></td><td>{flow.status==="active"?<button onClick={()=>change(flow,"paused")}><Pause/> Pausar</button>:flow.status!=="archived"?<button onClick={()=>change(flow,"active")}><Play/> Ativar</button>:"—"}</td></tr>)}{!flows.length?<tr><td colSpan={5}>Nenhum fluxo criado. Comece por uma automação rápida acima.</td></tr>:null}</tbody></table></div></section>
 </div>
}
