"use client";
import {Copy,Edit3,Plus,RefreshCw,Save,X} from "lucide-react";
import {useEffect,useState} from "react";
import {getSupabaseBrowserClient} from "../lib/supabase-client";

type CaravanRow={id:string;name:string;slug:string;destination:string;month:number|null;year:number|null;departure_date:string|null;return_date:string|null;duration_days:number|null;status_public:string;status_internal:string;short_description:string|null;cover_image:string|null;priority:number;published:boolean};
type FormState=Record<string,string|number|boolean>;
const empty:FormState={name:"",slug:"",destination:"",month:"",year:"",departure_date:"",return_date:"",duration_days:"",status_public:"disponivel",short_description:"",cover_image:"",priority:"100",published:true};
const fields=[ ["name","Nome *","text"],["slug","Slug *","text"],["destination","Destinos *","text"],["month","Mês","number"],["year","Ano","number"],["departure_date","Saída","date"],["return_date","Retorno","date"],["duration_days","Duração em dias","number"],["priority","Prioridade","number"],["cover_image","Imagem","url"] ];

export function AdminCaravans(){
  const[rows,setRows]=useState<CaravanRow[]>([]);const[form,setForm]=useState<FormState>(empty);const[editing,setEditing]=useState<string|null>(null);const[open,setOpen]=useState(false);const[message,setMessage]=useState("");
  async function load(){const s=getSupabaseBrowserClient();if(!s)return;const{data,error}=await s.from("caravans").select("id,name,slug,destination,month,year,departure_date,return_date,duration_days,status_public,status_internal,short_description,cover_image,priority,published").order("priority").order("year").order("month");setMessage(error?"Não foi possível carregar as caravanas.":"");setRows((data??[]) as CaravanRow[])}
  useEffect(()=>{load()},[]);
  function values(row:CaravanRow):FormState{return Object.fromEntries(Object.entries(row).map(([key,value])=>[key,typeof value==="boolean"?value:String(value??"")]))}
  function edit(row:CaravanRow){setEditing(row.id);setForm(values(row));setOpen(true)}
  function duplicate(row:CaravanRow){setEditing(null);setForm({...values(row),name:`${row.name} — cópia`,slug:`${row.slug}-copia`,published:false,priority:"100"});setOpen(true)}
  async function save(){const s=getSupabaseBrowserClient();if(!s)return;const payload={name:String(form.name),slug:String(form.slug),destination:String(form.destination),month:form.month?Number(form.month):null,year:form.year?Number(form.year):null,departure_date:form.departure_date||null,return_date:form.return_date||null,duration_days:form.duration_days?Number(form.duration_days):null,status_public:String(form.status_public),status_internal:"confirmada",short_description:form.short_description||null,cover_image:form.cover_image||null,priority:Number(form.priority||100),published:Boolean(form.published)};const result=editing?await s.from("caravans").update(payload).eq("id",editing):await s.from("caravans").insert(payload);if(result.error){setMessage("Não foi possível salvar. Confirme sua permissão e os campos obrigatórios.");return}setMessage("Caravana salva com segurança.");setOpen(false);setEditing(null);setForm(empty);load()}
  const required=rows.filter(row=>!row.month||!row.year||!row.departure_date||!row.return_date||!row.duration_days||!row.short_description||!row.cover_image);
  return <section className="crm-panel"><div className="crm-panel-head"><div><h2>Catálogo de caravanas</h2><p>Cadastre, edite, duplique, publique e priorize as saídas.</p></div><div className="crm-actions"><button onClick={load}><RefreshCw/>Atualizar</button><button onClick={()=>{setForm(empty);setEditing(null);setOpen(true)}}><Plus/>Nova caravana</button></div></div>
    {required.length?<div className="crm-required"><b>Dados necessários para publicação cronológica</b><p>{required.length} registro(s) ainda precisam de mês, ano, saída, retorno, duração, descrição ou imagem.</p></div>:null}{message?<div className="crm-alert">{message}</div>:null}
    {open?<div className="crm-editor"><header><h3>{editing?"Editar caravana":"Nova caravana"}</h3><button aria-label="Fechar" onClick={()=>setOpen(false)}><X/></button></header><div>{fields.map(([key,label,type])=><label key={key}>{label}<input type={type} value={String(form[key]??"")} onChange={event=>setForm(current=>({...current,[key]:event.target.value}))}/></label>)}<label>Status<select value={String(form.status_public)} onChange={event=>setForm(current=>({...current,status_public:event.target.value}))}><option value="disponivel">Disponível</option><option value="ultimas_vagas">Últimas vagas</option><option value="esgotada">Esgotada</option><option value="encerrada">Encerrada</option></select></label><label className="crm-wide">Descrição<textarea value={String(form.short_description??"")} onChange={event=>setForm(current=>({...current,short_description:event.target.value}))}/></label><label className="crm-check"><input type="checkbox" checked={Boolean(form.published)} onChange={event=>setForm(current=>({...current,published:event.target.checked}))}/> Publicada</label></div><button className="crm-save" onClick={save}><Save/>Salvar caravana</button></div>:null}
    <div className="crm-table-wrap"><table><thead><tr><th>Nome</th><th>Período</th><th>Duração</th><th>Status</th><th>Prioridade</th><th>Publicada</th><th>Ações</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.name}</td><td>{row.month&&row.year?`${row.month}/${row.year}`:"Preencher"}</td><td>{row.duration_days?`${row.duration_days} dias`:"Preencher"}</td><td>{row.status_public}</td><td>{row.priority}</td><td>{row.published?"Sim":"Não"}</td><td><div className="crm-row-actions"><button onClick={()=>edit(row)} aria-label={`Editar ${row.name}`}><Edit3/></button><button onClick={()=>duplicate(row)} aria-label={`Duplicar ${row.name}`}><Copy/></button></div></td></tr>)}</tbody></table></div>
  </section>
}
