"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect,useMemo,useState,type ReactNode } from "react";
import { BarChart3,BookOpen,CalendarCheck,Car,ClipboardList,CreditCard,FileCheck,Images,LayoutDashboard,LogOut,Map,Megaphone,Menu,MessageCircle,Settings,Users,UserRoundCheck,X } from "lucide-react";
import { canAccessModule,getAuthenticatedCrmUser,moduleFromPath,roleLabel,type CrmProfile } from "../lib/crm-auth";
import { getSupabaseBrowserClient } from "../lib/supabase-client";

const links=[[LayoutDashboard,"Dashboard","/admin/dashboard","dashboard"],[MessageCircle,"Caixa de entrada","/admin/atendimento","atendimento"],[Megaphone,"Campanhas e Disparos","/admin/campanhas","campanhas"],[Map,"Pipeline","/admin/pipeline","pipeline"],[Users,"Leads","/admin/leads","leads"],[ClipboardList,"Tarefas","/admin/tarefas","tarefas"],[UserRoundCheck,"Clientes","/admin/clientes","clientes"],[CalendarCheck,"Reservas","/admin/reservas","reservas"],[CreditCard,"Pagamentos","/admin/pagamentos","pagamentos"],[FileCheck,"Documentos","/admin/documentos","documentos"],[Car,"Caravanas","/admin/caravanas","caravanas"],[Images,"Conteúdo","/admin/experiencias","experiencias"],[BarChart3,"Relatórios","/admin/relatorios","relatorios"],[BookOpen,"Equipe","/admin/equipe","equipe"],[Settings,"Configurações","/admin/configuracoes","configuracoes"],[Settings,"Notificações","/admin/configuracoes/notificacoes","configuracoes"]] as const;

export function AdminShell({children,title}:{children:ReactNode;title:string}){const[ready,setReady]=useState(false);const[configured,setConfigured]=useState(true);const[menu,setMenu]=useState(false);const[profile,setProfile]=useState<CrmProfile|null>(null);const base=process.env.NEXT_PUBLIC_BASE_PATH??"";const pathname=usePathname();const currentModule=moduleFromPath(pathname);useEffect(()=>{const client=getSupabaseBrowserClient();if(!client){setConfigured(false);setReady(true);return}let active=true;getAuthenticatedCrmUser(client).then(user=>{if(!active)return;if(!user){window.location.replace(`${base}/admin/login/`);return}setProfile(user.profile);setReady(true)});const{data}=client.auth.onAuthStateChange(event=>{if(event==="SIGNED_OUT")window.location.replace(`${base}/admin/login/`)});return()=>{active=false;data.subscription.unsubscribe()}},[base]);const visibleLinks=useMemo(()=>profile?links.filter(([, , ,module])=>canAccessModule(profile.role,module)):[],[profile]);async function logout(){const client=getSupabaseBrowserClient();if(client)await client.auth.signOut({scope:"local"});window.location.replace(`${base}/admin/login/`)}if(!ready)return <main className="admin-loading" aria-live="polite">Validando acesso seguro…</main>;if(!configured)return <main className="admin-setup"><h1>CRM preparado para conexão</h1><p>Configure as variáveis públicas do Supabase para ativar a autenticação. Nenhuma credencial é armazenada no GitHub Pages.</p><Link href="/admin/login">Voltar ao login</Link></main>;if(!profile)return <main className="admin-loading">Redirecionando para o login…</main>;if(!canAccessModule(profile.role,currentModule))return <main className="admin-access-denied"><div><h1>Acesso restrito</h1><p>O perfil {roleLabel(profile.role)} não possui permissão para este módulo.</p><Link href="/admin/dashboard">Voltar ao dashboard</Link><button onClick={logout}><LogOut/>Sair com segurança</button></div></main>;return <div className="crm"><aside className={menu?"open":""}><div className="crm-brand">VP <span>CRM</span></div><nav>{visibleLinks.map(([Icon,label,href])=><Link href={href} key={href} onClick={()=>setMenu(false)}><Icon/>{label}</Link>)}</nav><div className="crm-user"><strong>{profile.full_name}</strong><span>{roleLabel(profile.role)}</span></div><button onClick={logout}><LogOut/>Sair</button></aside><main><header><button className="crm-menu" aria-label={menu?"Fechar menu":"Abrir menu"} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><div><small>Viagem Perfeita Turismo · {roleLabel(profile.role)}</small><h1>{title}</h1></div></header>{children}</main></div>}
