"use client";

import {useEffect,useState} from "react";
import {AlertTriangle,Bot,CalendarCheck,CheckCircle2,Clock3,Headphones,MailWarning,Users} from "lucide-react";
import {getSupabaseBrowserClient} from "../lib/supabase-client";

type Metrics={today:number;month:number;unassigned:number;overdue:number;confirmed:number;emailFailures:number;emailPending:number};
type Sla={open_conversations:number;waiting_over_sla:number;ai_active:number;human_active:number;avg_first_response_minutes:number};
const empty:Metrics={today:0,month:0,unassigned:0,overdue:0,confirmed:0,emailFailures:0,emailPending:0};

export function AdminDashboard(){
 const[m,setM]=useState<Metrics>(empty);const[sla,setSla]=useState<Sla|null>(null);const[error,setError]=useState("");
 useEffect(()=>{(async()=>{const s=getSupabaseBrowserClient();if(!s)return;const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()).toISOString(),month=new Date(now.getFullYear(),now.getMonth(),1).toISOString(),from=month.slice(0,10),to=now.toISOString().slice(0,10);const[a,b,c,d,e,f,g,performance]=await Promise.all([s.from("leads").select("id",{count:"exact",head:true}).gte("created_at",today),s.from("leads").select("id",{count:"exact",head:true}).gte("created_at",month),s.from("leads").select("id",{count:"exact",head:true}).is("assigned_to",null),s.from("tasks").select("id",{count:"exact",head:true}).lt("due_at",now.toISOString()).neq("status","concluida"),s.from("reservations").select("id",{count:"exact",head:true}).eq("status","confirmada"),s.from("email_notifications").select("id",{count:"exact",head:true}).eq("status","falhou"),s.from("email_notifications").select("id",{count:"exact",head:true}).in("status",["pendente","processando"]),s.rpc("crm_performance_center",{date_from:from,date_to:to})]);if(a.error){setError("Não foi possível carregar os indicadores.");return}setM({today:a.count??0,month:b.count??0,unassigned:c.count??0,overdue:d.count??0,confirmed:e.count??0,emailFailures:f.count??0,emailPending:g.count??0});if(!performance.error&&performance.data)setSla((performance.data as {sla:Sla}).sla)})()},[]);
 const items=[[Users,"Novos leads hoje",m.today],[CalendarCheck,"Leads no mês",m.month],[Clock3,"Leads sem responsável",m.unassigned],[AlertTriangle,"Tarefas vencidas",m.overdue],[CheckCircle2,"Reservas confirmadas",m.confirmed],[MailWarning,"Falhas de e-mail",m.emailFailures],[Clock3,"E-mails pendentes",m.emailPending]] as const;
 return <>{error?<div className="crm-alert">{error}</div>:null}<div className="crm-metrics">{items.map(([Icon,label,value])=><div key={label}><Icon/><span>{label}</span><b>{value}</b></div>)}</div><section className="crm-panel performance-overview"><div><h2>Central de atendimento</h2><p>Operação humana e IA em tempo real, com alerta para conversas fora do SLA.</p></div>{sla?<div className="sla-strip"><span><Headphones/><small>Em aberto</small><b>{sla.open_conversations}</b></span><span className={sla.waiting_over_sla?"is-critical":""}><AlertTriangle/><small>Fora do SLA</small><b>{sla.waiting_over_sla}</b></span><span><Clock3/><small>1ª resposta média</small><b>{sla.avg_first_response_minutes} min</b></span><span><Bot/><small>IA ativa</small><b>{sla.ai_active}</b></span><span><Users/><small>Humano ativo</small><b>{sla.human_active}</b></span></div>:<p className="crm-muted">Aplique a migration da Central de Performance para ativar os indicadores avançados.</p>}</section></>;
}
