"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { Check,ChevronLeft,ChevronRight,Download,Edit3,History,LoaderCircle,Plus,RefreshCw,Search,Trash2,UserRoundCheck,X } from "lucide-react";
import { getAuthenticatedCrmUser,type CrmProfile } from "../lib/crm-auth";
import { getSupabaseBrowserClient } from "../lib/supabase-client";

type ModuleName="leads"|"tarefas"|"clientes"|"reservas"|"pagamentos"|"documentos";
type Field={name:string;label:string;type?:"text"|"email"|"tel"|"number"|"date"|"datetime-local"|"select"|"textarea";required?:boolean;options?:readonly string[];relation?:"customers"|"caravans"|"reservations"|"leads"|"profiles"};
type Row=Record<string,unknown>; type Option={value:string;label:string};
type Config={table:string;title:string;singular:string;description:string;columns:Array<[string,string]>;fields:Field[];search:string[];statusField?:string;statusOptions?:readonly string[];writeRoles:readonly string[]};
const leadStatuses=["novo_lead","primeiro_contato","em_atendimento","roteiro_enviado","proposta_enviada","aguardando_resposta","negociacao","reserva_iniciada","aguardando_pagamento","reserva_confirmada","documentacao_pendente","passageiro_confirmado","perdido","arquivado"] as const;
const configs:Record<ModuleName,Config>={
  leads:{table:"leads",title:"Leads",singular:"lead",description:"Contatos comerciais recebidos e acompanhados pela equipe.",columns:[["name","Nome"],["phone","Telefone"],["email","E-mail"],["status","Etapa"],["temperature","Temperatura"],["source","Origem"],["created_at","Entrada"]],search:["name","phone","email"],statusField:"status",statusOptions:leadStatuses,writeRoles:["administrador","gestor","consultor"],fields:[{name:"name",label:"Nome",required:true},{name:"phone",label:"Telefone",type:"tel",required:true},{name:"email",label:"E-mail",type:"email"},{name:"city",label:"Cidade"},{name:"state",label:"Estado"},{name:"source",label:"Origem",required:true},{name:"status",label:"Etapa",type:"select",options:leadStatuses,required:true},{name:"temperature",label:"Temperatura",type:"select",options:["frio","morno","quente","prioridade"],required:true}]},
  tarefas:{table:"tasks",title:"Tarefas",singular:"tarefa",description:"Próximas ações, retornos e pendências distribuídas entre os atendentes.",columns:[["title","Tarefa"],["lead_name","Lead"],["assignee_name","Responsável"],["due_at","Prazo"],["priority","Prioridade"],["status","Situação"]],search:["title","description","lead_name","assignee_name"],statusField:"status",statusOptions:["pendente","em_andamento","concluida","cancelada"],writeRoles:["administrador","gestor","consultor"],fields:[{name:"title",label:"Título",required:true},{name:"description",label:"Descrição",type:"textarea"},{name:"lead_id",label:"Lead",type:"select",relation:"leads"},{name:"reservation_id",label:"Reserva",type:"select",relation:"reservations"},{name:"assigned_to",label:"Responsável",type:"select",relation:"profiles"},{name:"due_at",label:"Prazo",type:"datetime-local"},{name:"priority",label:"Prioridade",type:"select",options:["baixa","media","alta","urgente"],required:true},{name:"status",label:"Situação",type:"select",options:["pendente","em_andamento","concluida","cancelada"],required:true},{name:"task_type",label:"Tipo",type:"select",options:["follow_up","documentacao","pagamento","reserva","atendimento","outro"]}]},
  clientes:{table:"customers",title:"Clientes",singular:"cliente",description:"Pessoas convertidas e seu relacionamento com a empresa.",columns:[["name","Nome"],["phone","Telefone"],["email","E-mail"],["city","Cidade"],["status","Situação"],["created_at","Cadastro"]],search:["name","phone","email"],statusField:"status",statusOptions:["ativo","inativo","arquivado"],writeRoles:["administrador","gestor","consultor"],fields:[{name:"name",label:"Nome",required:true},{name:"phone",label:"Telefone",type:"tel"},{name:"email",label:"E-mail",type:"email"},{name:"city",label:"Cidade"},{name:"state",label:"Estado"},{name:"birth_date",label:"Nascimento",type:"date"},{name:"status",label:"Situação",type:"select",options:["ativo","inativo","arquivado"],required:true}]},
  reservas:{table:"reservations",title:"Reservas",singular:"reserva",description:"Reservas vinculadas a clientes, caravanas e passageiros.",columns:[["reservation_code","Código"],["customer_name","Cliente"],["caravan_name","Caravana"],["status","Situação"],["travelers_count","Viajantes"],["payment_status","Pagamento"],["final_value","Valor final"]],search:["reservation_code"],statusField:"status",statusOptions:["pre_reserva","aguardando_pagamento","confirmada","cancelada","concluida"],writeRoles:["administrador","gestor","consultor"],fields:[{name:"customer_id",label:"Cliente",type:"select",relation:"customers",required:true},{name:"caravan_id",label:"Caravana",type:"select",relation:"caravans"},{name:"reservation_code",label:"Código da reserva"},{name:"status",label:"Situação",type:"select",options:["pre_reserva","aguardando_pagamento","confirmada","cancelada","concluida"],required:true},{name:"travelers_count",label:"Viajantes",type:"number",required:true},{name:"departure_city",label:"Cidade de embarque"},{name:"final_value",label:"Valor final",type:"number"},{name:"payment_status",label:"Pagamento",type:"select",options:["pendente","parcial","pago","atrasado","estornado"],required:true}]},
  pagamentos:{table:"payments",title:"Pagamentos",singular:"pagamento",description:"Parcelas, vencimentos e conciliação financeira das reservas.",columns:[["reservation_label","Reserva"],["description","Descrição"],["amount","Valor"],["due_date","Vencimento"],["status","Situação"],["payment_method","Forma"]],search:["description","external_reference"],statusField:"status",statusOptions:["pendente","pago","atrasado","cancelado","estornado"],writeRoles:["administrador","gestor"],fields:[{name:"reservation_id",label:"Reserva",type:"select",relation:"reservations",required:true},{name:"description",label:"Descrição",required:true},{name:"amount",label:"Valor",type:"number",required:true},{name:"due_date",label:"Vencimento",type:"date"},{name:"status",label:"Situação",type:"select",options:["pendente","pago","atrasado","cancelado","estornado"],required:true},{name:"payment_method",label:"Forma de pagamento"},{name:"external_reference",label:"Referência externa"}]},
  documentos:{table:"documents",title:"Documentos",singular:"documento",description:"Pendências documentais vinculadas às reservas e passageiros.",columns:[["reservation_label","Reserva"],["document_type","Documento"],["status","Situação"],["expires_at","Validade"],["updated_at","Atualização"]],search:["document_type","notes"],statusField:"status",statusOptions:["nao_solicitado","solicitado","recebido","em_analise","aprovado","rejeitado","vencido"],writeRoles:["administrador","gestor","consultor"],fields:[{name:"reservation_id",label:"Reserva",type:"select",relation:"reservations",required:true},{name:"document_type",label:"Tipo de documento",required:true},{name:"status",label:"Situação",type:"select",options:["nao_solicitado","solicitado","recebido","em_analise","aprovado","rejeitado","vencido"],required:true},{name:"expires_at",label:"Validade",type:"date"},{name:"notes",label:"Observações",type:"textarea"}]}
};
const defaults:Record<ModuleName,Row>={leads:{source:"Site",status:"novo_lead",temperature:"morno"},tarefas:{priority:"media",status:"pendente",task_type:"follow_up"},clientes:{status:"ativo"},reservas:{status:"pre_reserva",travelers_count:1,payment_status:"pendente"},pagamentos:{status:"pendente"},documentos:{status:"nao_solicitado"}};
const pageSize=20;
function display(value:unknown,key:string){if(value===null||value===undefined||value==="")return "—";if(key.includes("value")||key==="amount")return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value));if(key.endsWith("_at")||key.endsWith("_date")){const date=new Date(String(value));return Number.isNaN(date.getTime())?"—":new Intl.DateTimeFormat("pt-BR",key.endsWith("_at")?{dateStyle:"short",timeStyle:"short"}:{dateStyle:"short"}).format(date)}return String(value).replaceAll("_"," ");}
function formValue(value:unknown,type:Field["type"]){if(!value)return "";if(type==="datetime-local"){const date=new Date(String(value));if(Number.isNaN(date.getTime()))return "";const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}return String(value)}
function normalizePhone(value:unknown){return String(value??"").replace(/\D/g,"");}

export function CrmOperationalModule({module}:{module:ModuleName}){
  const cfg=configs[module]; const[rows,setRows]=useState<Row[]>([]); const[loading,setLoading]=useState(true); const[message,setMessage]=useState(""); const[query,setQuery]=useState(""); const[status,setStatus]=useState(""); const[page,setPage]=useState(0); const[form,setForm]=useState<Row|null>(null); const[profile,setProfile]=useState<CrmProfile|null>(null); const[relations,setRelations]=useState<Record<string,Option[]>>({}); const[saving,setSaving]=useState(false); const[selectedFile,setSelectedFile]=useState<File|null>(null); const[history,setHistory]=useState<Row[]|null>(null);
  const canWrite=Boolean(profile&&cfg.writeRoles.includes(profile.role));
  const load=useCallback(async()=>{setLoading(true);setMessage("");const client=getSupabaseBrowserClient();if(!client){setLoading(false);setMessage("Supabase não configurado.");return}const user=await getAuthenticatedCrmUser(client);setProfile(user?.profile??null);const{data,error}=await client.from(cfg.table).select("*").order("created_at",{ascending:false}).limit(250);if(error){setMessage("Não foi possível carregar os registros com sua permissão atual.");setRows([])}else{let result=(data??[]) as Row[];if(module==="reservas"){const[cust,cars]=await Promise.all([client.from("customers").select("id,name"),client.from("caravans").select("id,name")]);const cm=new Map((cust.data??[]).map(item=>[item.id,item.name])),tm=new Map((cars.data??[]).map(item=>[item.id,item.name]));result=result.map(row=>({...row,customer_name:cm.get(String(row.customer_id))??"—",caravan_name:tm.get(String(row.caravan_id))??"—"}))}if(module==="pagamentos"||module==="documentos"){const res=await client.from("reservations").select("id,reservation_code");const rm=new Map((res.data??[]).map(item=>[item.id,item.reservation_code||String(item.id).slice(0,8)]));result=result.map(row=>({...row,reservation_label:rm.get(String(row.reservation_id))??"—"}))}if(module==="tarefas"){const[leads,profiles]=await Promise.all([client.from("leads").select("id,name"),client.from("profiles").select("id,full_name")]);const lm=new Map((leads.data??[]).map(item=>[item.id,item.name])),pm=new Map((profiles.data??[]).map(item=>[item.id,item.full_name]));result=result.map(row=>({...row,lead_name:lm.get(String(row.lead_id))??"—",assignee_name:pm.get(String(row.assigned_to))??"Não atribuído"}))}setRows(result)}setLoading(false)},[cfg.table,module]);
  useEffect(()=>{load()},[load]);
  useEffect(()=>{if(!form)return;const client=getSupabaseBrowserClient();if(!client)return;(async()=>{const needed=[...new Set(cfg.fields.flatMap(field=>field.relation?[field.relation]:[]))];const result:Record<string,Option[]>={};for(const relation of needed){if(relation==="customers"){const{data}=await client.from("customers").select("id,name").order("name");result[relation]=(data??[]).map(row=>({value:row.id,label:row.name}))}if(relation==="caravans"){const{data}=await client.from("caravans").select("id,name").order("name");result[relation]=(data??[]).map(row=>({value:row.id,label:row.name}))}if(relation==="reservations"){const{data}=await client.from("reservations").select("id,reservation_code").order("created_at",{ascending:false});result[relation]=(data??[]).map(row=>({value:row.id,label:row.reservation_code||String(row.id).slice(0,8)}))}if(relation==="leads"){const{data}=await client.from("leads").select("id,name").order("name");result[relation]=(data??[]).map(row=>({value:row.id,label:row.name}))}if(relation==="profiles"){const{data}=await client.from("profiles").select("id,full_name").eq("active",true).order("full_name");result[relation]=(data??[]).map(row=>({value:row.id,label:row.full_name}))}}setRelations(result)})()},[form,cfg.fields]);
  const filtered=useMemo(()=>rows.filter(row=>(!status||row[cfg.statusField??""]===status)&&(!query||cfg.search.some(key=>String(row[key]??"").toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR"))))),[rows,status,query,cfg]);
  const visible=filtered.slice(page*pageSize,(page+1)*pageSize); const pages=Math.max(1,Math.ceil(filtered.length/pageSize));
  useEffect(()=>{if(page>=pages)setPage(pages-1)},[page,pages]);
  function open(row?:Row){setMessage("");setSelectedFile(null);setForm(row?{...row}:{...defaults[module]})}
  async function convertLead(row:Row){const client=getSupabaseBrowserClient();if(!client)return;setMessage("");const{error}=await client.rpc("convert_lead_to_customer",{target_lead_id:row.id});if(error){setMessage(`Não foi possível converter o lead: ${error.message}`);return}setMessage("Lead convertido em cliente com sucesso.");await load()}
  function exportCsv(){const headers=cfg.columns.map(([,label])=>label);const csv=[headers,...filtered.map(row=>cfg.columns.map(([key])=>String(row[key]??"").replaceAll('"','""')))];const content=csv.map(line=>line.map(value=>`"${value}"`).join(";")).join("\n");const blob=new Blob(["\uFEFF",content],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`${module}-${new Date().toISOString().slice(0,10)}.csv`;anchor.click();URL.revokeObjectURL(url)}
  async function remove(row:Row){if(!profile||!window.confirm(`Excluir este ${cfg.singular}? Esta ação ficará registrada no histórico.`))return;const client=getSupabaseBrowserClient();if(!client)return;setMessage("");const{error}=await client.from(cfg.table).delete().eq("id",row.id);if(error){setMessage(`Não foi possível excluir: ${error.message}`);return}setMessage(`${cfg.singular.charAt(0).toUpperCase()+cfg.singular.slice(1)} excluído com sucesso.`);await load()}
  async function showHistory(row:Row){const client=getSupabaseBrowserClient();if(!client)return;const{data,error}=await client.from("audit_logs").select("id,action,user_id,before_data,after_data,created_at").eq("entity_id",row.id).order("created_at",{ascending:false}).limit(50);if(error){setMessage("O histórico está disponível apenas para administradores e gestores.");return}setHistory((data??[]) as Row[])}
  async function save(event:React.FormEvent){event.preventDefault();if(!form||!profile)return;setSaving(true);setMessage("");const client=getSupabaseBrowserClient();if(!client){setSaving(false);setMessage("Supabase não configurado.");return}const payload:Row={};for(const field of cfg.fields){const value=form[field.name];payload[field.name]=value===""?null:field.type==="number"&&value!==null?Number(value):value}if(module==="leads"){payload.phone_normalized=normalizePhone(payload.phone);payload.organization_id=profile.organization_id}if(["tarefas","clientes","reservas"].includes(module))payload.organization_id=profile.organization_id;if(module==="tarefas"){if(!form.id)payload.created_by=profile.id;payload.completed_at=payload.status==="concluida"?(form.completed_at??new Date().toISOString()):null}if(module==="reservas"&&!form.id)payload.created_by=profile.id;if(module==="documentos")payload.uploaded_by=profile.id;let recordId=String(form.id??"");let error:unknown=null;if(form.id){const result=await client.from(cfg.table).update(payload).eq("id",form.id);error=result.error}else if(module==="clientes"){const result=await client.rpc("crm_create_customer",{customer_data:payload});error=result.error;recordId=String(result.data??"")}else if(module==="reservas"){const result=await client.rpc("crm_create_reservation",{reservation_data:payload});error=result.error;recordId=String(result.data??"")}else{const result=await client.from(cfg.table).insert(payload).select("id").single();error=result.error;recordId=String(result.data?.id??"")}if(error){setMessage(`Não foi possível salvar: ${(error as {message:string}).message}`);setSaving(false);return}if(module==="documentos"&&selectedFile&&recordId){if(selectedFile.size>10*1024*1024){setMessage("O registro foi salvo, mas o arquivo excede o limite de 10 MB.");setSaving(false);return}const safeName=selectedFile.name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${profile.organization_id}/${String(form.reservation_id)}/${recordId}/${Date.now()}-${safeName}`;const upload=await client.storage.from("private-documents").upload(path,selectedFile,{upsert:false});if(upload.error){setMessage("O registro foi salvo, mas o arquivo não pôde ser enviado. Tente anexá-lo novamente.");setSaving(false);return}await client.from("documents").update({file_path:path,uploaded_by:profile.id,updated_at:new Date().toISOString()}).eq("id",recordId)}setForm(null);setSelectedFile(null);setSaving(false);setMessage(`${cfg.singular.charAt(0).toUpperCase()+cfg.singular.slice(1)} salvo com sucesso.`);await load()}
  return <section className="crm-panel crm-operational"><div className="crm-panel-head"><div><h2>{cfg.title}</h2><p>{cfg.description}</p></div><div className="crm-head-actions"><button onClick={exportCsv} disabled={filtered.length===0}><Download/>Exportar</button><button onClick={load}><RefreshCw/>Atualizar</button>{canWrite?<button className="crm-primary" onClick={()=>open()}><Plus/>Novo {cfg.singular}</button>:null}</div></div>
    <div className="crm-filters"><label><Search/><input aria-label={`Buscar em ${cfg.title}`} placeholder="Pesquisar por nome, telefone ou referência" value={query} onChange={event=>{setQuery(event.target.value);setPage(0)}}/></label>{cfg.statusOptions?<select aria-label="Filtrar por situação" value={status} onChange={event=>{setStatus(event.target.value);setPage(0)}}><option value="">Todas as situações</option>{cfg.statusOptions.map(option=><option key={option}>{option}</option>)}</select>:null}<span>{filtered.length} registro(s)</span></div>
    {message?<div className="crm-alert" role="status">{message}</div>:null}{loading?<div className="crm-loading"><LoaderCircle className="spin"/>Carregando dados…</div>:visible.length===0?<div className="crm-empty">Nenhum registro encontrado com os filtros atuais.</div>:<div className="crm-table-wrap"><table><thead><tr>{cfg.columns.map(([,label])=><th key={label}>{label}</th>)}{canWrite?<th>Ações</th>:null}</tr></thead><tbody>{visible.map((row,index)=><tr key={String(row.id??index)}>{cfg.columns.map(([key])=><td key={key}>{display(row[key],key)}</td>)}{canWrite?<td><div className="crm-row-actions"><button className="crm-icon-button" aria-label={`Editar ${cfg.singular}`} onClick={()=>open(row)}><Edit3/></button><button className="crm-icon-button" aria-label={`Histórico de ${cfg.singular}`} onClick={()=>showHistory(row)}><History/></button>{module==="leads"&&!row.converted_customer_id?<button className="crm-icon-button" aria-label="Converter lead em cliente" title="Converter em cliente" onClick={()=>convertLead(row)}><UserRoundCheck/></button>:null}<button className="crm-icon-button crm-danger" aria-label={`Excluir ${cfg.singular}`} onClick={()=>remove(row)}><Trash2/></button></div></td>:null}</tr>)}</tbody></table></div>}
    <div className="crm-pagination"><button disabled={page===0} onClick={()=>setPage(value=>value-1)}><ChevronLeft/>Anterior</button><span>Página {page+1} de {pages}</span><button disabled={page+1>=pages} onClick={()=>setPage(value=>value+1)}>Próxima<ChevronRight/></button></div>
    {form?<div className="crm-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setForm(null)}}><form className="crm-modal" onSubmit={save}><header><div><small>{form.id?"Editar":"Cadastrar"}</small><h2>{cfg.singular.charAt(0).toUpperCase()+cfg.singular.slice(1)}</h2></div><button type="button" aria-label="Fechar" onClick={()=>setForm(null)}><X/></button></header><div className="crm-form-grid">{cfg.fields.map(field=><label key={field.name} className={field.type==="textarea"?"wide":""}>{field.label}{field.type==="select"?<select required={field.required} value={String(form[field.name]??"")} onChange={event=>setForm({...form,[field.name]:event.target.value})}><option value="">Selecione</option>{field.relation?(relations[field.relation]??[]).map(option=><option value={option.value} key={option.value}>{option.label}</option>):field.options?.map(option=><option key={option}>{option.replaceAll("_"," ")}</option>)}</select>:field.type==="textarea"?<textarea value={String(form[field.name]??"")} onChange={event=>setForm({...form,[field.name]:event.target.value})}/>:<input type={field.type??"text"} step={field.type==="number"?"0.01":undefined} min={field.type==="number"?0:undefined} required={field.required} value={formValue(form[field.name],field.type)} onChange={event=>setForm({...form,[field.name]:event.target.value})}/>}</label>)}{module==="documentos"?<label className="wide">Arquivo privado (PDF, imagem ou documento; máximo 10 MB)<input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx" onChange={event=>setSelectedFile(event.target.files?.[0]??null)}/>{form.file_path?<small>Arquivo atual protegido no armazenamento privado.</small>:null}</label>:null}</div><footer><button type="button" onClick={()=>setForm(null)}>Cancelar</button><button className="crm-primary" type="submit" disabled={saving}>{saving?<LoaderCircle className="spin"/>:<Check/>}{saving?"Salvando…":"Salvar"}</button></footer></form></div>:null}
    {history?<div className="crm-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setHistory(null)}}><section className="crm-modal crm-history" role="dialog" aria-modal="true" aria-label="Histórico do registro"><header><div><small>Auditoria</small><h2>Histórico do registro</h2></div><button type="button" aria-label="Fechar histórico" onClick={()=>setHistory(null)}><X/></button></header><div className="crm-history-list">{history.length===0?<p>Nenhuma alteração registrada.</p>:history.map(item=><article key={String(item.id)}><strong>{display(item.action,"action")}</strong><time>{display(item.created_at,"created_at")}</time><p>{item.after_data?JSON.stringify(item.after_data):"Registro removido ou anonimizado."}</p></article>)}</div></section></div>:null}
  </section>
}
