export type BlogCategory={slug:string;name:string;description:string};
export type BlogArticle={slug:string;title:string;excerpt:string;category:string;readingTime:string;sections:Array<{title:string;content:string}>;keywords:string[]};
export const blogCategories:BlogCategory[]=[
  ["israel","Israel","Contexto, preparação e experiências na Terra Santa."],
  ["egito","Egito","História, cultura e planejamento para conhecer o Egito."],
  ["jordania","Jordânia","Petra, Monte Nebo e os caminhos históricos da Jordânia."],
  ["turquia","Turquia","Cidades antigas e caminhos do cristianismo primitivo."],
  ["grecia","Grécia","Cultura clássica e os caminhos do apóstolo Paulo."],
  ["documentacao","Documentação","Orientações para uma preparação internacional responsável."],
  ["dicas","Dicas","Organização, bagagem, saúde e experiência do viajante."],
  ["passaporte","Passaporte","Validade, conservação e cuidados antes do embarque."],
  ["seguranca","Segurança","Decisões responsáveis antes e durante viagens internacionais."],
  ["turismo-religioso","Turismo religioso","Conteúdo para compreender e viver viagens de fé."],
].map(([slug,name,description])=>({slug,name,description}));
export const blogArticles:BlogArticle[]=[
  {slug:"como-se-preparar-para-uma-viagem-a-israel",title:"Como se preparar para uma viagem a Israel",excerpt:"Um guia responsável para organizar documentos, expectativas, ritmo e acompanhamento antes da Terra Santa.",category:"israel",readingTime:"6 min",keywords:["viagem para Israel","caravana para Israel"],sections:[{title:"Comece pelo propósito",content:"Entender o que você busca ajuda a escolher um roteiro coerente: conteúdo bíblico, história, cultura e momentos de contemplação podem aparecer em proporções diferentes."},{title:"Confirme os requisitos vigentes",content:"Regras de entrada, documentos e recomendações podem mudar. Consulte fontes oficiais e confirme as orientações com a equipe responsável pela viagem."},{title:"Prepare-se para o ritmo",content:"Roteiros pela Terra Santa podem envolver caminhadas, variação de clima e dias intensos. Informe necessidades de mobilidade e saúde antes da contratação."}]},
  {slug:"o-que-e-turismo-religioso",title:"Turismo religioso: propósito, cultura e responsabilidade",excerpt:"Entenda como uma viagem de fé pode unir espiritualidade, conhecimento histórico e respeito aos destinos visitados.",category:"turismo-religioso",readingTime:"5 min",keywords:["turismo religioso","viagem de fé"],sections:[{title:"Mais que visitar lugares",content:"O turismo religioso cria oportunidades de aprendizado, contemplação e convivência, sem dispensar planejamento profissional e respeito cultural."},{title:"A importância da mediação",content:"Coordenação, guias e líderes ajudam a contextualizar lugares e organizar a experiência do grupo com clareza."},{title:"Escolha com transparência",content:"Antes de contratar, verifique roteiro, serviços incluídos, regras, condições de pagamento e suporte oferecido."}]},
  {slug:"passaporte-para-viagem-internacional",title:"Passaporte para viagem internacional: cuidados essenciais",excerpt:"O que conferir no documento antes de reservar e embarcar em uma jornada internacional.",category:"passaporte",readingTime:"4 min",keywords:["passaporte","documentação de viagem"],sections:[{title:"Validade",content:"Cada destino pode exigir uma validade mínima além da data de retorno. Confirme a regra oficial aplicável ao seu itinerário."},{title:"Dados e conservação",content:"Verifique nome, dados pessoais, páginas disponíveis e condições físicas do documento."},{title:"Cópias e segurança",content:"Mantenha cópias protegidas e evite compartilhar imagens completas do passaporte por canais sem proteção adequada."}]},
  {slug:"seguranca-em-viagens-internacionais",title:"Segurança em viagens internacionais começa no planejamento",excerpt:"Como avaliar informações, suporte, documentos e decisões operacionais com responsabilidade.",category:"seguranca",readingTime:"5 min",keywords:["segurança em viagens","viagem internacional"],sections:[{title:"Informação atualizada",content:"Cenários operacionais e orientações oficiais podem mudar. Reavalie condições próximas ao embarque."},{title:"Rede de apoio",content:"Tenha contatos da coordenação, seguro, representação consular e documentos necessários disponíveis."},{title:"Decisões responsáveis",content:"Alterações de roteiro devem considerar orientação oficial, fornecedores e segurança do grupo, nunca apenas expectativas comerciais."}]},
];
export const getArticle=(slug:string)=>blogArticles.find(article=>article.slug===slug);
export const getCategory=(slug:string)=>blogCategories.find(category=>category.slug===slug);
