export type Destination = { slug: string; name: string; headline: string; introduction: string; history: string; spirituality: string; places: string[]; bestPeriod: string; documentation: string; image: string; faqs: Array<[string,string]> };

const generalNotice = "Regras de entrada, vistos, vacinas e validade documental podem mudar. Confirme sempre as exigências nos canais oficiais e com a equipe antes de contratar ou embarcar.";
export const destinations: Destination[] = [
  { slug:"israel", name:"Israel", headline:"História e fé vividas de perto", introduction:"Uma jornada por paisagens, cidades e tradições que ajudam a compreender contextos bíblicos e culturais.", history:"Jerusalém, Galileia e outras regiões guardam camadas de história de diferentes povos e tradições.", spirituality:"Para muitos viajantes, visitar Israel é uma oportunidade de contemplação, aprendizado e renovação da fé.", places:["Jerusalém","Mar da Galileia","Nazaré","Monte das Oliveiras","Mar Morto"], bestPeriod:"A definição do período deve considerar clima, calendário religioso, operação aérea e perfil do grupo.", documentation:generalNotice, image:"https://images.unsplash.com/photo-1548018560-c7196548e84d?auto=format&fit=crop&w=1200&q=75", faqs:[["A viagem exige preparo físico?","O ritmo depende do roteiro confirmado. Informe mobilidade reduzida ou necessidades específicas antes da contratação."],["Existe acompanhamento em português?","A composição da equipe e dos guias será informada na proposta oficial de cada viagem."]] },
  { slug:"egito", name:"Egito", headline:"Uma civilização que atravessa milênios", introduction:"Patrimônio, arqueologia e paisagens ligadas a importantes narrativas históricas.", history:"O Egito reúne monumentos e centros urbanos que ajudam a compreender uma das civilizações mais influentes da Antiguidade.", spirituality:"O destino dialoga com narrativas bíblicas e oferece uma experiência profunda de contexto histórico.", places:["Cairo","Pirâmides de Gizé","Museus do Cairo","Rio Nilo","Monte Sinai, conforme roteiro"], bestPeriod:"A época ideal varia conforme temperaturas, lotação, disponibilidade e roteiro combinado.", documentation:generalNotice, image:"https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=1200&q=75", faqs:[["O visto está incluído?","A necessidade, emissão e inclusão serão informadas na proposta oficial."],["Posso combinar Egito e Israel?","Sim. Consulte as caravanas disponíveis e receba da equipe as condições oficiais da saída escolhida."]] },
  { slug:"jordania", name:"Jordânia", headline:"Deserto, patrimônio e hospitalidade", introduction:"Paisagens marcantes e sítios históricos entre Petra, Amã e o vale do Jordão.", history:"A Jordânia reúne vestígios de civilizações e rotas comerciais que conectaram o Oriente Médio.", spirituality:"Lugares ligados a tradições bíblicas favorecem contemplação e contextualização histórica.", places:["Petra","Amã","Monte Nebo","Wadi Rum","Betânia além do Jordão"], bestPeriod:"O período deve ser definido conforme clima desértico e operação do grupo.", documentation:generalNotice, image:"https://images.unsplash.com/photo-1548786811-dd6e453ccca7?auto=format&fit=crop&w=1200&q=75", faqs:[["A visita a Petra exige caminhada?","Há deslocamentos a pé. Condições de acessibilidade devem ser avaliadas no roteiro confirmado."]] },
  { slug:"turquia", name:"Turquia", headline:"Encontro de continentes e tradições", introduction:"História cristã, patrimônio e cultura entre cidades antigas e centros contemporâneos.", history:"Anatólia e Istambul preservam testemunhos de impérios e antigas comunidades cristãs.", spirituality:"Éfeso e outros sítios ajudam a contextualizar o cristianismo primitivo.", places:["Istambul","Éfeso","Capadócia","Pérgamo","Antioquia, conforme roteiro"], bestPeriod:"A escolha depende das regiões incluídas e do perfil do grupo.", documentation:generalNotice, image:"https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=75", faqs:[["A Capadócia está sempre incluída?","Somente quando constar no roteiro oficial da experiência escolhida."]] },
  { slug:"grecia", name:"Grécia", headline:"Cultura clássica e caminhos de Paulo", introduction:"Uma viagem entre história antiga, paisagens mediterrâneas e lugares das primeiras comunidades cristãs.", history:"A Grécia influenciou profundamente filosofia, arte, política e cultura ocidental.", spirituality:"Atenas, Corinto e outras cidades oferecem contexto às viagens e cartas do apóstolo Paulo.", places:["Atenas","Corinto","Tessalônica","Meteora","Filipos"], bestPeriod:"Clima, fluxo turístico e conexões aéreas devem ser avaliados para cada grupo.", documentation:generalNotice, image:"https://images.unsplash.com/photo-1504512485720-7d83a16ee930?auto=format&fit=crop&w=1200&q=75", faqs:[["É uma viagem apenas religiosa?","Os roteiros podem equilibrar conteúdo religioso, histórico e cultural."]] },
  { slug:"italia", name:"Itália", headline:"Arte, história e espiritualidade", introduction:"Cidades que reúnem patrimônio cristão, arte e experiências culturais.", history:"Roma e outras regiões italianas preservam séculos de história europeia e cristã.", spirituality:"Basílicas, comunidades e caminhos de peregrinação podem integrar roteiros com diferentes perfis.", places:["Roma","Vaticano","Assis","Florença","Orvieto"], bestPeriod:"A escolha considera clima, eventos, lotação e disponibilidade dos serviços.", documentation:generalNotice, image:"https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=1200&q=75", faqs:[["A audiência papal é garantida?","Não. Eventos e acessos dependem da agenda oficial e nunca devem ser tratados como garantidos."]] },
  { slug:"europa", name:"Europa", headline:"Roteiros culturais e bíblicos sob medida", introduction:"Combinações de países e cidades conforme propósito, ritmo e perfil do grupo.", history:"A Europa reúne patrimônio de diferentes períodos e tradições, permitindo roteiros temáticos diversos.", spirituality:"Caminhos cristãos, arte sacra e comunidades históricas podem compor experiências de fé.", places:["Itália","Grécia","Turquia","França","Portugal"], bestPeriod:"O melhor período depende dos países, orçamento, clima e objetivo da viagem.", documentation:generalNotice, image:"https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=1200&q=75", faqs:[["É possível criar um roteiro exclusivo?","Sim. A equipe pode estudar uma viagem personalizada para grupos fechados."]] },
];
export function getDestination(slug:string){return destinations.find((item)=>item.slug===slug)}
