export type TripInternalStatus="confirmada"|"arquivada";
export type TripPublicStatus="disponivel"|"ultimas_vagas"|"esgotada"|"encerrada";
export type TripCategory="religioso"|"cultural"|"personalizado";
export type ItineraryDay={day:number;date?:string;city?:string;title:string;description?:string;hotel?:string;meals?:string[];activities?:string[];transportation?:string;notes?:string};
export type Trip={id:string;name:string;slug:string;subtitle:string;shortDescription:string;fullDescription:string;coverImage:string;gallery:string[];videoUrl?:string;primaryDestination:string;countries:string[];cities:string[];departureDate?:string;returnDate?:string;month?:number;year?:number;days?:number;nights?:number;departureCity?:string;availableAirports:string[];category:TripCategory;tripType:string;leader?:string;coordinator?:string;airline?:string;hotelCategory?:string;meals?:string;guide?:string;totalSeats?:number;remainingSeats?:number;publicStatus:TripPublicStatus;internalStatus:TripInternalStatus;featured:boolean;priority:number;published:boolean;price?:number;currency?:"BRL"|"USD"|"EUR";deposit?:number;installments?:string;cashDiscount?:string;conditionValidUntil?:string;commercialNotes?:string;itinerary:ItineraryDay[];included:string[];notIncluded:string[];optionalServices:string[];documentation:string[];faq:Array<{question:string;answer:string}>;seo:{title:string;description:string;noIndex?:boolean};differentiator?:string};

export const publicStatusLabels:Record<TripPublicStatus,string>={disponivel:"Disponível",ultimas_vagas:"Últimas vagas",esgotada:"Esgotada",encerrada:"Encerrada"};
export const internalStatusLabels:Record<TripInternalStatus,string>={confirmada:"Confirmada",arquivada:"Arquivada"};
const commonDocumentation=["Passaporte válido conforme as regras dos destinos","Vistos e autorizações conforme nacionalidade e roteiro","Requisitos sanitários vigentes na data do embarque"];
const commonFaq=[{question:"Como consultar valores e condições?",answer:"Preencha o formulário desta caravana. A equipe apresentará somente valores, disponibilidade e condições oficiais vigentes."},{question:"Como recebo o roteiro completo?",answer:"Solicite o roteiro pelo formulário da caravana. Quando houver versão detalhada cadastrada, a equipe enviará o material oficial."},{question:"A reserva é confirmada pelo WhatsApp?",answer:"Não. A reserva depende da confirmação comercial, aceite das condições e procedimentos informados pela equipe."}];
const defaultNotIncluded=["Despesas pessoais","Documentação pessoal, quando não prevista no contrato","Refeições e serviços não mencionados na proposta oficial","Passeios opcionais, gorjetas e bagagens adicionais quando não incluídos"];
type TripInput=Omit<Trip,"availableAirports"|"publicStatus"|"internalStatus"|"published"|"featured"|"priority"|"included"|"notIncluded"|"optionalServices"|"documentation"|"faq"|"seo"> & Partial<Pick<Trip,"availableAirports"|"featured"|"priority"|"included"|"notIncluded"|"optionalServices"|"documentation"|"faq">>;
function confirmed(input:TripInput):Trip{return{...input,availableAirports:input.availableAirports??(input.departureCity?[input.departureCity]:[]),publicStatus:"disponivel",internalStatus:"confirmada",published:true,featured:input.featured??false,priority:input.priority??100,included:input.included??[],notIncluded:input.notIncluded??defaultNotIncluded,optionalServices:input.optionalServices??[],documentation:input.documentation??commonDocumentation,faq:input.faq??commonFaq,seo:{title:`${input.name} | Viagem Perfeita Turismo`,description:input.shortDescription}}}
function briefItinerary(items:Array<[string,string]>):ItineraryDay[]{return items.map(([city,title],index)=>({day:index+1,city,title}))}

export const trips:Trip[]=[
  confirmed({id:"trip_egito_jordania_israel_2026",name:"Caravana Egito, Jordânia e Israel — Novembro 2026",slug:"egito-jordania-israel-novembro-2026",subtitle:"Egito, Jordânia e Israel",shortDescription:"Três países unidos por história, cultura e experiências de profundo significado.",fullDescription:"Uma jornada internacional em grupo pela riqueza histórica do Egito, pelas paisagens da Jordânia e pelos lugares de fé de Israel. A proposta combina conhecimento, convivência, acompanhamento e momentos de espiritualidade, com os serviços detalhados somente na apresentação comercial oficial.",coverImage:"https://images.unsplash.com/photo-1664833202404-101f375ff555?auto=format&fit=crop&w=2400&q=92",gallery:["https://images.unsplash.com/photo-1664833202404-101f375ff555?auto=format&fit=crop&w=2400&q=92","https://images.unsplash.com/photo-1763966461585-41a652f12dd3?auto=format&fit=crop&w=2400&q=92"],primaryDestination:"Egito, Jordânia e Israel",countries:["Egito","Jordânia","Israel"],cities:[],month:11,year:2026,availableAirports:[],category:"religioso",tripType:"Caravana internacional",itinerary:[],featured:true,priority:1,differentiator:"Próxima saída prioritária"}),
  confirmed({id:"trip_paris_egito_israel_2027",name:"Caravana Paris, Egito e Israel — Março 2027",slug:"paris-egito-israel-marco-2027",subtitle:"Paris, Egito e Israel",shortDescription:"Uma experiência entre patrimônio europeu, história milenar e lugares de fé.",fullDescription:"Uma caravana internacional que conecta Paris, a herança histórica do Egito e a experiência espiritual de Israel. O roteiro valoriza cultura, história, convivência em grupo e acompanhamento próximo, com detalhes operacionais apresentados exclusivamente nas condições oficiais.",coverImage:"https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=900&q=72",gallery:["https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=900&q=72"],primaryDestination:"Paris, Egito e Israel",countries:["França","Egito","Israel"],cities:["Paris"],month:3,year:2027,availableAirports:[],category:"religioso",tripType:"Caravana internacional",itinerary:[],featured:true,priority:2,differentiator:"Destaque prioritário"}),
  confirmed({id:"trip_turquia_grecia_2027",name:"Turquia e Grécia — Passos de Paulo",slug:"turquia-grecia-2027",subtitle:"Passos de Paulo",shortDescription:"Uma jornada pelos caminhos das primeiras comunidades cristãs.",fullDescription:"Cidades históricas e lugares ligados ao cristianismo primitivo compõem uma experiência de cultura, conhecimento e fé em grupo.",coverImage:"https://images.unsplash.com/photo-1504512485720-7d83a16ee930?auto=format&fit=crop&w=900&q=72",gallery:["https://images.unsplash.com/photo-1504512485720-7d83a16ee930?auto=format&fit=crop&w=900&q=72"],primaryDestination:"Turquia e Grécia",countries:["Turquia","Grécia"],cities:["Istambul","Éfeso","Atenas","Corinto"],month:3,year:2027,days:14,nights:13,departureCity:"São Paulo",category:"religioso",tripType:"Caravana internacional",itinerary:briefItinerary([["Istambul","Chegada"],["Éfeso","Patrimônio histórico"],["Atenas","Caminhos de Paulo"]])}),
  confirmed({id:"trip_jordania_israel_2027",name:"Jordânia e Israel — Jornada da Promessa",slug:"jordania-israel-2027",subtitle:"Jornada da Promessa",shortDescription:"Paisagens, patrimônio e contextos bíblicos entre Jordânia e Israel.",fullDescription:"Uma experiência em grupo que aproxima história, arqueologia e espiritualidade entre dois destinos marcantes.",coverImage:"https://images.unsplash.com/photo-1548786811-dd6e453ccca7?auto=format&fit=crop&w=900&q=72",gallery:[],primaryDestination:"Jordânia e Israel",countries:["Jordânia","Israel"],cities:["Amã","Petra","Jerusalém"],month:5,year:2027,days:13,nights:12,departureCity:"São Paulo",category:"religioso",tripType:"Caravana internacional",itinerary:briefItinerary([["Amã","Chegada"],["Petra","Experiência histórica"],["Jerusalém","Chegada à Terra Santa"]])}),
  confirmed({id:"trip_italia_2027",name:"Itália — Caminhos de São Francisco",slug:"italia-2027",subtitle:"Caminhos de São Francisco",shortDescription:"Arte, cultura e espiritualidade em cidades históricas da Itália.",fullDescription:"Uma caravana que propõe vivências culturais e espirituais em um roteiro de patrimônio, contemplação e convivência.",coverImage:"https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=900&q=72",gallery:[],primaryDestination:"Itália",countries:["Itália"],cities:["Roma","Assis","Florença"],month:6,year:2027,days:10,nights:9,departureCity:"São Paulo",category:"religioso",tripType:"Caravana internacional",itinerary:briefItinerary([["Roma","Chegada"],["Assis","Caminhos franciscanos"],["Florença","Patrimônio cultural"]])}),
  confirmed({id:"trip_israel_2027",name:"Israel — Caminhos da Fé",slug:"israel-2027",subtitle:"Caminhos da Fé",shortDescription:"Fé, história e cultura nos lugares que dão contexto às Escrituras.",fullDescription:"Uma experiência de grupo por Israel com proposta histórica, cultural e espiritual, organizada para favorecer conhecimento e contemplação.",coverImage:"https://images.unsplash.com/photo-1763966461585-41a652f12dd3?auto=format&fit=crop&w=2400&q=92",gallery:["https://images.unsplash.com/photo-1763966461585-41a652f12dd3?auto=format&fit=crop&w=2400&q=92"],primaryDestination:"Israel",countries:["Israel","Itália"],cities:["Jerusalém","Galileia","Roma"],month:9,year:2027,days:11,nights:10,departureCity:"São Paulo",category:"religioso",tripType:"Caravana internacional",itinerary:briefItinerary([["Roma","Chegada e acolhimento"],["Roma","Roma cristã"],["Jerusalém","Chegada à Terra Santa"]])}),
  confirmed({id:"trip_emirados_egito_2027",name:"Emirados e Egito — Entre História e Futuro",slug:"emirados-egito-2027",subtitle:"Entre História e Futuro",shortDescription:"Arquitetura contemporânea e patrimônio milenar em uma mesma jornada.",fullDescription:"Uma viagem cultural em grupo que combina os contrastes dos Emirados Árabes Unidos com a herança histórica do Egito.",coverImage:"https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=72",gallery:[],primaryDestination:"Emirados e Egito",countries:["Emirados Árabes Unidos","Egito"],cities:["Dubai","Abu Dhabi","Cairo"],month:10,year:2027,days:13,nights:12,departureCity:"São Paulo",category:"cultural",tripType:"Viagem cultural",itinerary:briefItinerary([["Dubai","Chegada"],["Abu Dhabi","Experiência cultural"],["Cairo","Patrimônio histórico"]])}),
  confirmed({id:"trip_israel_egito_2027",name:"Israel e Egito — Raízes do Êxodo",slug:"israel-egito-2027",subtitle:"Raízes do Êxodo",shortDescription:"História milenar e caminhos bíblicos entre Egito e Israel.",fullDescription:"Uma caravana de conhecimento e fé que conecta a civilização egípcia aos contextos históricos e espirituais de Israel.",coverImage:"https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=900&q=72",gallery:["https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=900&q=72"],primaryDestination:"Egito e Israel",countries:["Egito","Israel"],cities:["Cairo","Jerusalém","Galileia"],month:11,year:2027,days:12,nights:11,departureCity:"São Paulo",category:"religioso",tripType:"Caravana internacional",itinerary:briefItinerary([["Cairo","Chegada e acolhimento"],["Cairo","Patrimônio histórico"],["Jerusalém","Caminhos bíblicos"]])}),
];

export function isTripPublic(trip:Trip){return trip.published&&trip.internalStatus==="confirmada"}
export const publishedTrips=trips.filter(isTripPublic).sort((a,b)=>a.priority-b.priority||tripTimestamp(a)-tripTimestamp(b));
export const featuredTrips=publishedTrips.filter(trip=>trip.featured).sort((a,b)=>a.priority-b.priority);
export function getTripBySlug(slug:string){return trips.find(trip=>trip.slug===slug)}
export function getPublishedTripBySlug(slug:string){return publishedTrips.find(trip=>trip.slug===slug)}
export function tripTimestamp(trip:Trip){return new Date(trip.departureDate??`${trip.year??9999}-${String(trip.month??12).padStart(2,"0")}-01T00:00:00Z`).getTime()}
export function formatTripPeriod(trip:Trip){if(trip.departureDate&&trip.returnDate){const f=new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"});return`${f.format(new Date(trip.departureDate))} a ${f.format(new Date(trip.returnDate))}`}if(trip.month&&trip.year){const month=new Intl.DateTimeFormat("pt-BR",{month:"long",timeZone:"UTC"}).format(new Date(Date.UTC(trip.year,trip.month-1,1)));return`${month.charAt(0).toUpperCase()}${month.slice(1)} de ${trip.year}`}return""}
export function formatTripPrice(trip:Trip){if(!trip.price||!trip.currency)return"Consulte valores e condições de pagamento.";return new Intl.NumberFormat("pt-BR",{style:"currency",currency:trip.currency}).format(trip.price)}
