export type TripInternalStatus="confirmada"|"arquivada";
import {officialItineraries} from "./official-itineraries";
export type TripPublicStatus="disponivel"|"ultimas_vagas"|"lista_espera"|"em_planejamento"|"esgotada"|"encerrada";
export type TripCategory="religioso"|"cultural"|"personalizado";
export type ItineraryDay={day:number;date?:string;city?:string;title:string;description?:string;hotel?:string;meals?:string[];activities?:string[];transportation?:string;notes?:string};
export type Trip={id:string;name:string;slug:string;subtitle:string;shortDescription:string;fullDescription:string;coverImage:string;gallery:string[];videoUrl?:string;primaryDestination:string;countries:string[];cities:string[];departureDate?:string;returnDate?:string;month?:number;year?:number;days?:number;nights?:number;departureCity?:string;availableAirports:string[];category:TripCategory;tripType:string;leader?:string;coordinator?:string;airline?:string;hotelCategory?:string;meals?:string;guide?:string;totalSeats?:number;remainingSeats?:number;publicStatus:TripPublicStatus;internalStatus:TripInternalStatus;featured:boolean;priority:number;published:boolean;price?:number;currency?:"BRL"|"USD"|"EUR";deposit?:number;installments?:string;cashDiscount?:string;conditionValidUntil?:string;commercialNotes?:string;itineraryTitle?:string;itinerarySubtitle?:string;itinerary:ItineraryDay[];included:string[];notIncluded:string[];optionalServices:string[];documentation:string[];faq:Array<{question:string;answer:string}>;seo:{title:string;description:string;noIndex?:boolean};differentiator?:string};

export const publicStatusLabels:Record<TripPublicStatus,string>={disponivel:"Disponível",ultimas_vagas:"Últimas vagas",lista_espera:"Lista de espera",em_planejamento:"Em planejamento",esgotada:"Esgotada",encerrada:"Encerrada"};
export const internalStatusLabels:Record<TripInternalStatus,string>={confirmada:"Confirmada",arquivada:"Arquivada"};
const commonDocumentation=["Passaporte válido conforme as regras dos destinos","Vistos e autorizações conforme nacionalidade e roteiro","Requisitos sanitários vigentes na data do embarque"];
const commonFaq=[{question:"Como consultar valores e condições?",answer:"Preencha o formulário desta caravana. A equipe apresentará somente valores, disponibilidade e condições oficiais vigentes."},{question:"Como recebo o roteiro completo?",answer:"Solicite o roteiro pelo formulário da caravana. Quando houver versão detalhada cadastrada, a equipe enviará o material oficial."},{question:"A reserva é confirmada pelo WhatsApp?",answer:"Não. A reserva depende da confirmação comercial, aceite das condições e procedimentos informados pela equipe."}];
const defaultNotIncluded=["Despesas pessoais","Documentação pessoal, quando não prevista no contrato","Refeições e serviços não mencionados na proposta oficial","Passeios opcionais, gorjetas e bagagens adicionais quando não incluídos"];
type TripInput=Omit<Trip,"availableAirports"|"publicStatus"|"internalStatus"|"published"|"featured"|"priority"|"included"|"notIncluded"|"optionalServices"|"documentation"|"faq"|"seo"> & Partial<Pick<Trip,"availableAirports"|"featured"|"priority"|"included"|"notIncluded"|"optionalServices"|"documentation"|"faq">>;
function confirmed(input:TripInput):Trip{return{...input,availableAirports:input.availableAirports??(input.departureCity?[input.departureCity]:[]),publicStatus:"disponivel",internalStatus:"confirmada",published:true,featured:input.featured??false,priority:input.priority??100,included:input.included??[],notIncluded:input.notIncluded??defaultNotIncluded,optionalServices:input.optionalServices??[],documentation:input.documentation??commonDocumentation,faq:input.faq??commonFaq,seo:{title:`${input.name} | Viagem Perfeita Turismo`,description:input.shortDescription}}}
function briefItinerary(items:Array<[string,string]>):ItineraryDay[]{return items.map(([city,title],index)=>({day:index+1,city,title}))}

export const trips:Trip[]=[
  confirmed({
    id:"trip_egito_jordania_israel_2026",name:"Caravana Egito, Jordânia e Israel — Novembro de 2026",slug:"egito-jordania-israel-novembro-2026",subtitle:"Egito, Jordânia e Israel",shortDescription:"Três países unidos por história, cultura e experiências de profundo significado.",fullDescription:"Uma jornada internacional em grupo por Egito, Jordânia e Israel, com acompanhamento da Viagem Perfeita. O roteiro detalhado está sendo revisado e será apresentado pela equipe na proposta oficial.",coverImage:"https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=900&q=72",gallery:["https://images.unsplash.com/photo-1539650116574-75c0c6d73f6e?auto=format&fit=crop&w=900&q=72","/media/official-instagram/israel-caravana-eliana.jpg"],primaryDestination:"Egito, Jordânia e Israel",countries:["Egito","Jordânia","Israel"],cities:[],month:11,year:2026,days:14,departureCity:"São Paulo",category:"religioso",tripType:"Caravana internacional",itineraryTitle:"Roteiro detalhado em atualização",itinerarySubtitle:"Solicite à nossa equipe a versão oficial desta caravana.",hotelCategory:"Hotéis categoria 3 e 4 estrelas",meals:"Meia pensão conforme os destinos informados no pacote",itinerary:[],included:["Passagem aérea internacional de ida e volta, com saída de São Paulo","Acompanhamento da equipe Viagem Perfeita durante toda a viagem, oferecendo suporte e assistência do início ao fim","Traslados Aeroporto ⇄ Hotel em todos os destinos","Ônibus executivo de turismo com ar-condicionado e Wi-Fi","Guias locais especializados falando português","Hospedagem em hotéis categoria 3 e 4 estrelas","Hospedagem em regime de meia pensão no Egito","Hospedagem em regime de meia pensão na Jordânia","Hospedagem em regime de meia pensão em Israel","Acomodação em apartamentos duplos ou triplos","Entradas nos principais atrativos turísticos e locais bíblicos conforme o roteiro","Roteiro exclusivo desenvolvido pela Viagem Perfeita","Kit exclusivo Gift Viagem Perfeita","Seguro viagem com cobertura médica internacional"],featured:true,priority:1,differentiator:"Próxima saída prioritária"
  }),
  confirmed({
    id:"trip_paris_egito_israel_2027",name:"Caravana Paris, Egito e Israel — Março de 2027",slug:"paris-egito-israel-marco-2027",subtitle:"Paris, Egito e Israel",shortDescription:"Uma jornada pela história, fé e cultura.",fullDescription:"Uma caravana internacional que conecta Paris, a herança histórica do Egito e a experiência espiritual de Israel, com acompanhamento da Viagem Perfeita durante toda a jornada.",coverImage:"https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=900&q=72",gallery:["https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=900&q=72"],primaryDestination:"Paris, Egito e Israel",countries:["França","Egito","Israel"],cities:["Paris","Cairo","Monte Sinai","Mar Vermelho","Galileia","Nazaré","Jerusalém","Jericó","Mar Morto","Massada"],month:3,year:2027,days:14,departureCity:"São Paulo",category:"religioso",tripType:"Caravana internacional",itineraryTitle:"PARIS, EGITO E ISRAEL",itinerarySubtitle:"UMA JORNADA PELA HISTÓRIA, FÉ E CULTURA",hotelCategory:"Hotéis categoria 3 e 4 estrelas",meals:"Café da manhã em Paris e meia pensão no Egito e em Israel",itinerary:[
      {day:1,city:"Brasil · Paris",title:"Brasil — Paris",description:"Encontro do grupo no Aeroporto Internacional de Guarulhos para orientações, entrega de materiais de viagem e embarque com destino a Paris. Pernoite a bordo."},
      {day:2,city:"Paris — França",title:"Paris — França",description:"Chegada em Paris, recepção pela equipe local e início do passeio panorâmico pela Cidade Luz. Ao final do dia, traslado para o hotel, hospedagem e descanso.",activities:["Torre Eiffel","Arco do Triunfo","Champs-Élysées","Praça da Concórdia","Museu do Louvre, área externa","Ópera Garnier","Catedral de Notre-Dame, área externa","Passeio às margens do Rio Sena"]},
      {day:3,city:"Paris · Cairo",title:"Paris — Cairo",description:"Após o café da manhã, continuação dos passeios por Paris e tempo livre para compras e fotografias. No horário programado, traslado ao aeroporto e embarque com destino ao Cairo. Chegada, recepção, traslado para o hotel e hospedagem."},
      {day:4,city:"Cairo — Egito",title:"Cairo — Egito",description:"Após o café da manhã, visita aos monumentos mais importantes do Egito Antigo, com tempo para compras e experiências culturais. Retorno ao hotel e hospedagem.",activities:["Complexo das Pirâmides de Gizé","Grande Esfinge","Museu Egípcio do Cairo","Tesouros de Tutancâmon","Múmias e artefatos históricos","Fábrica de papiros","Grande Bazar Khan El Khalili"]},
      {day:5,city:"Monte Sinai · Deserto do Negev",title:"Monte Sinai — Réplica dos Tabernáculos",description:"Saída em direção à Península do Sinai, com reflexões sobre a jornada do povo hebreu rumo à Terra Prometida. À noite, início da subida ao Monte Sinai para aqueles que desejarem participar.",activities:["Réplica dos Tabernáculos no Deserto do Negev","Estudos bíblicos sobre o Tabernáculo e o sacerdócio","Momentos de oração e ministração"]},
      {day:6,city:"Monte Sinai · Mar Vermelho",title:"Monte Sinai — Mar Vermelho",description:"Chegada ao topo do Monte Sinai para contemplação do nascer do sol, oração, adoração e reflexão. Descida da montanha e viagem para um resort às margens do Mar Vermelho. Tempo livre para descanso e hospedagem."},
      {day:7,city:"Egito · Israel · Galileia",title:"Egito — Israel — Galileia",description:"Após o café da manhã, procedimentos de fronteira e entrada em Israel. Chegada à região da Galileia e início das visitas aos locais relacionados ao ministério de Jesus. Hospedagem na Galileia.",activities:["Passeio de barco pelo Mar da Galileia, com louvor e ministração","Rio Jordão e renovação dos votos batismais","Cafarnaum","Casa de Pedro","Antiga Sinagoga de Cafarnaum","Tabgha","Local tradicional da reconciliação de Pedro com Jesus","Monte das Bem-Aventuranças","Magdala"]},
      {day:8,city:"Nazaré · Monte Tabor · Jerusalém",title:"Nazaré — Monte Tabor — Jerusalém",description:"Após o café da manhã, viagem para Nazaré. Ao final da tarde, viagem para Jerusalém, entrada na Cidade Santa e hospedagem.",activities:["Vila de Nazaré","Basílica da Anunciação","Monte do Precipício","Monte Tabor","Local tradicional da Transfiguração de Jesus"]},
      {day:9,city:"Jericó · Mar Morto · Massada",title:"Jericó — Mar Morto — Massada",description:"Após o café da manhã, viagem para o Vale do Jordão. Retorno a Jerusalém e hospedagem.",activities:["Jericó","Vista do Monte da Tentação","Sicômoro de Zaqueu","Mar Morto, com tempo para banho e relaxamento","Fortaleza de Massada"]},
      {day:10,city:"Jerusalém Antiga",title:"Jerusalém Antiga",description:"Dia dedicado aos passos finais de Jesus, com tempo livre no Mercado Árabe e nos tradicionais mercados de Jerusalém. Tentativa de visita ao Terraço do Monte do Templo, conforme autorização das autoridades locais. Hospedagem.",activities:["Monte das Oliveiras","Vista panorâmica de Jerusalém","Jardim do Getsêmani","Igreja de Todas as Nações","Muro das Lamentações","Monte Sião","Cenáculo","Túmulo simbólico do Rei Davi","Casa de Caifás","Igreja de Sant’Ana","Tanque de Betesda","Via Dolorosa","Santo Sepulcro"]},
      {day:11,city:"Cidade de Davi · Jerusalém",title:"Cidade de Davi — Túmulo Vazio — Museu de Israel",description:"Após o café da manhã, visitas, tempo livre para oração e compras e hospedagem.",activities:["Cidade de Davi","Túneis arqueológicos","Escadarias do Templo","Poço de Siloé","Jardim do Túmulo","Celebração da Ceia do Senhor","Momento de adoração","Museu de Israel","Santuário do Livro","Manuscritos do Mar Morto"]},
      {day:12,city:"Jerusalém",title:"Jerusalém",description:"Dia dedicado a passeios complementares, oração, compras e experiências espirituais na Cidade Santa. Possibilidade de visitas adicionais conforme a programação local. Hospedagem."},
      {day:13,city:"Jerusalém",title:"Jerusalém — Dia livre",description:"Dia livre para descanso, compras, experiências pessoais, visita ao Muro das Lamentações e momentos devocionais. Hospedagem."},
      {day:14,city:"Israel · Brasil",title:"Israel — Brasil",description:"Em horário previamente informado, traslado ao Aeroporto Ben Gurion. Procedimentos de embarque e retorno ao Brasil. Chegada ao Aeroporto Internacional de Guarulhos. Fim dos serviços."}
    ],included:["Passagem aérea internacional de ida e volta, com saída de São Paulo","Passeios pelos principais pontos turísticos de Paris","Acompanhamento da equipe Viagem Perfeita durante toda a viagem","Traslados Aeroporto ⇄ Hotel em todos os destinos","Ônibus executivo de turismo com ar-condicionado e Wi-Fi","Guias locais especializados falando português","Hospedagem em hotéis categoria 3 e 4 estrelas","Café da manhã em Paris","Hospedagem em regime de meia pensão no Egito","Hospedagem em regime de meia pensão em Israel","Acomodação em apartamentos duplos ou triplos","Entradas nos principais atrativos turísticos e locais bíblicos conforme o roteiro","Roteiro exclusivo desenvolvido pela Viagem Perfeita","Kit exclusivo Gift Viagem Perfeita","Seguro viagem com cobertura médica internacional"],featured:true,priority:2,differentiator:"Destaque prioritário"
  }),
  confirmed({id:"trip_turquia_grecia_2027",name:"Turquia e Grécia — Passos de Paulo — 2027",slug:"turquia-grecia-2027",subtitle:"Passos de Paulo",shortDescription:"Uma jornada pelos caminhos das primeiras comunidades cristãs.",fullDescription:"Cidades históricas e lugares ligados ao cristianismo primitivo compõem uma experiência de cultura, conhecimento e fé em grupo.",coverImage:"https://images.unsplash.com/photo-1504512485720-7d83a16ee930?auto=format&fit=crop&w=900&q=72",gallery:["https://images.unsplash.com/photo-1504512485720-7d83a16ee930?auto=format&fit=crop&w=900&q=72"],primaryDestination:"Turquia e Grécia",countries:["Turquia","Grécia"],cities:["Istambul","Éfeso","Atenas","Corinto"],month:3,year:2027,days:14,nights:13,departureCity:"São Paulo",category:"religioso",tripType:"Caravana internacional",itinerary:briefItinerary([["Istambul","Chegada"],["Éfeso","Patrimônio histórico"],["Atenas","Caminhos de Paulo"]])}),
  confirmed({id:"trip_jordania_israel_2027",name:"Jordânia e Israel — Jornada da Promessa",slug:"jordania-israel-2027",subtitle:"Jornada da Promessa",shortDescription:"Paisagens, patrimônio e contextos bíblicos entre Jordânia e Israel.",fullDescription:"Uma experiência em grupo que aproxima história, arqueologia e espiritualidade entre dois destinos marcantes.",coverImage:"https://images.unsplash.com/photo-1548786811-dd6e453ccca7?auto=format&fit=crop&w=900&q=72",gallery:[],primaryDestination:"Jordânia e Israel",countries:["Jordânia","Israel"],cities:["Amã","Petra","Jerusalém"],month:5,year:2027,days:13,nights:12,departureCity:"São Paulo",category:"religioso",tripType:"Caravana internacional",itinerary:briefItinerary([["Amã","Chegada"],["Petra","Experiência histórica"],["Jerusalém","Chegada à Terra Santa"]])}),
  confirmed({id:"trip_italia_2027",name:"Itália — Caminhos de São Francisco",slug:"italia-2027",subtitle:"Caminhos de São Francisco",shortDescription:"Arte, cultura e espiritualidade em cidades históricas da Itália.",fullDescription:"Uma caravana que propõe vivências culturais e espirituais em um roteiro de patrimônio, contemplação e convivência.",coverImage:"https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=900&q=72",gallery:[],primaryDestination:"Itália",countries:["Itália"],cities:["Roma","Assis","Florença"],month:6,year:2027,days:10,nights:9,departureCity:"São Paulo",category:"religioso",tripType:"Caravana internacional",itinerary:briefItinerary([["Roma","Chegada"],["Assis","Caminhos franciscanos"],["Florença","Patrimônio cultural"]])}),
  confirmed({id:"trip_israel_2027",name:"Israel e Itália — Caminhos da Fé",slug:"israel-2027",subtitle:"Caminhos da Fé",shortDescription:"Fé, história e cultura nos lugares que dão contexto às Escrituras.",fullDescription:"Uma experiência de grupo por Israel e Itália com proposta histórica, cultural e espiritual, organizada para favorecer conhecimento e contemplação.",coverImage:"https://images.unsplash.com/photo-1548018560-c7196548e84d?auto=format&fit=crop&w=900&q=72",gallery:["https://images.unsplash.com/photo-1548018560-c7196548e84d?auto=format&fit=crop&w=900&q=72"],primaryDestination:"Israel e Itália",countries:["Israel","Itália"],cities:["Jerusalém","Galileia","Roma"],month:9,year:2027,days:11,nights:10,departureCity:"São Paulo",category:"religioso",tripType:"Caravana internacional",itinerary:briefItinerary([["Roma","Chegada e acolhimento"],["Roma","Roma cristã"],["Jerusalém","Chegada à Terra Santa"]])}),
  confirmed({id:"trip_emirados_egito_2027",name:"Emirados e Egito — Entre História e Futuro",slug:"emirados-egito-2027",subtitle:"Entre História e Futuro",shortDescription:"Arquitetura contemporânea e patrimônio milenar em uma mesma jornada.",fullDescription:"Uma viagem cultural em grupo que combina os contrastes dos Emirados Árabes Unidos com a herança histórica do Egito.",coverImage:"https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=72",gallery:[],primaryDestination:"Emirados e Egito",countries:["Emirados Árabes Unidos","Egito"],cities:["Dubai","Abu Dhabi","Cairo"],month:10,year:2027,days:13,nights:12,departureCity:"São Paulo",category:"cultural",tripType:"Viagem cultural",itinerary:briefItinerary([["Dubai","Chegada"],["Abu Dhabi","Experiência cultural"],["Cairo","Patrimônio histórico"]])}),
  confirmed({id:"trip_israel_egito_2027",name:"Israel e Egito — Raízes do Êxodo",slug:"israel-egito-2027",subtitle:"Raízes do Êxodo",shortDescription:"História milenar e caminhos bíblicos entre Israel e Egito.",fullDescription:"Uma caravana de conhecimento e fé que conecta os contextos históricos e espirituais de Israel à civilização egípcia.",coverImage:"https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=900&q=72",gallery:["https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=900&q=72"],primaryDestination:"Israel e Egito",countries:["Israel","Egito"],cities:["Cairo","Jerusalém","Galileia"],month:11,year:2027,days:12,nights:11,departureCity:"São Paulo",category:"religioso",tripType:"Caravana internacional",itinerary:briefItinerary([["Cairo","Chegada e acolhimento"],["Cairo","Patrimônio histórico"],["Jerusalém","Caminhos bíblicos"]])}),
];

const recurring2027Slugs=["paris-egito-israel-marco-2027","turquia-grecia-2027","jordania-israel-2027","italia-2027","israel-2027","emirados-egito-2027","israel-egito-2027"];
for(const trip of trips){
  const itinerary=officialItineraries[trip.slug];
  if(itinerary){
    trip.itinerary=itinerary;
    trip.itineraryTitle=trip.name.replace(/\s—\s(?:Março|Novembro) de \d{4}$/u,"").toUpperCase();
    trip.itinerarySubtitle=trip.subtitle;
    trip.hotelCategory="Hotéis categoria 4 e 5 estrelas ou similares";
    trip.departureCity="São Paulo";
    trip.availableAirports=["São Paulo (GRU)"];
  }
}
const recurring2028Trips=trips.filter((trip)=>recurring2027Slugs.includes(trip.slug)).map((trip):Trip=>{
  const name=trip.name.includes("2027")?trip.name.replace("2027","2028"):`${trip.name} — 2028`;
  return{...trip,id:trip.id.replace("2027","2028"),name,slug:trip.slug.replace("2027","2028"),year:2028,featured:false,priority:trip.priority+100,itinerary:trip.itinerary.map(item=>({...item,activities:item.activities?[...item.activities]:undefined})),seo:{title:`${name} | Viagem Perfeita Turismo`,description:trip.shortDescription}};
});
trips.push(...recurring2028Trips);

const officialPriorityCovers:Record<string,{coverImage:string;gallery:string[]}>= {
  "egito-jordania-israel-novembro-2026":{coverImage:"/media/israel/jerusalem-experiencia.jpg",gallery:["/media/israel/jerusalem-experiencia.jpg","/media/official-instagram/israel-caravana-eliana.jpg"]},
  "paris-egito-israel-marco-2027":{coverImage:"/media/israel/monte-das-oliveiras.jpg",gallery:["/media/israel/monte-das-oliveiras.jpg"]},
};
for(const trip of trips){const media=officialPriorityCovers[trip.slug];if(media)Object.assign(trip,media)}

export function isTripPublic(trip:Trip){return trip.published&&trip.internalStatus==="confirmada"}
export const publishedTrips=trips.filter(isTripPublic).sort((a,b)=>a.priority-b.priority||tripTimestamp(a)-tripTimestamp(b));
export const featuredTrips=publishedTrips.filter(trip=>trip.featured).sort((a,b)=>a.priority-b.priority);
export function getTripBySlug(slug:string){return trips.find(trip=>trip.slug===slug)}
export function getPublishedTripBySlug(slug:string){return publishedTrips.find(trip=>trip.slug===slug)}
export function tripTimestamp(trip:Trip){return new Date(trip.departureDate??`${trip.year??9999}-${String(trip.month??12).padStart(2,"0")}-01T00:00:00Z`).getTime()}
export function formatTripPeriod(trip:Trip){if(trip.departureDate&&trip.returnDate){const f=new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"});return`${f.format(new Date(trip.departureDate))} a ${f.format(new Date(trip.returnDate))}`}if(trip.month&&trip.year){const month=new Intl.DateTimeFormat("pt-BR",{month:"long",timeZone:"UTC"}).format(new Date(Date.UTC(trip.year,trip.month-1,1)));return`${month.charAt(0).toUpperCase()}${month.slice(1)} de ${trip.year}`}return""}
export function formatTripPrice(trip:Trip){if(!trip.price||!trip.currency)return"Valores e condições de pagamento sob consulta. Fale com nossa equipe e receba a proposta oficial desta caravana.";return new Intl.NumberFormat("pt-BR",{style:"currency",currency:trip.currency}).format(trip.price)}
