import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const clean=(value:unknown)=>typeof value==="string"?value.trim():value==null?"":String(value);
const escapeHtml=(value:unknown)=>clean(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]!));
const row=(label:string,value:unknown)=>clean(value)?`<tr><th style="padding:6px 12px 6px 0;text-align:left;vertical-align:top">${escapeHtml(label)}</th><td style="padding:6px 0">${escapeHtml(value)}</td></tr>`:"";

Deno.serve(async(request)=>{
  if(request.method==="OPTIONS")return new Response("ok",{headers:cors});
  const supabaseUrl=Deno.env.get("SUPABASE_URL");const serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");const resendKey=Deno.env.get("RESEND_API_KEY");
  const recipient=Deno.env.get("CRM_NOTIFICATION_EMAIL")||"viagemperfeitatrip@gmail.com";const from=Deno.env.get("CRM_FROM_EMAIL");const appUrl=(Deno.env.get("APP_URL")||"").replace(/\/$/,"");
  if(!supabaseUrl||!serviceKey)return new Response(JSON.stringify({status:"falhou"}),{status:500,headers:{...cors,"Content-Type":"application/json"}});
  const admin=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false}});let notificationId="";
  try{
    notificationId=clean((await request.json()).notificationId);if(!notificationId)throw new Error("notification_id_required");
    const {data:notification,error:queueError}=await admin.from("email_notifications").select("id,event_type,lead_id,subject,status,attempts").eq("id",notificationId).single();
    if(queueError||!notification)throw new Error("notification_not_found");if(notification.status==="enviado")return new Response(JSON.stringify({status:"enviado"}),{headers:{...cors,"Content-Type":"application/json"}});if(notification.attempts>=3)throw new Error("retry_limit_reached");
    const {data:claimed}=await admin.from("email_notifications").update({status:"processando",attempts:notification.attempts+1,updated_at:new Date().toISOString()}).eq("id",notificationId).in("status",["pendente","falhou"]).select("id").maybeSingle();if(!claimed)throw new Error("notification_already_processing");
    const {data:lead,error:leadError}=await admin.from("leads").select("id,name,phone,email,city,state,source,source_detail,utm_source,utm_medium,utm_campaign,landing_page,created_at").eq("id",notification.lead_id).single();if(leadError||!lead)throw new Error("lead_not_found");
    const {data:interest}=await admin.from("lead_interests").select("experience_name,destination,desired_period,duration,travelers_count,accommodation,departure_city,payment_preference,main_interest,custom_notes,created_at").eq("lead_id",lead.id).order("created_at",{ascending:false}).limit(1).maybeSingle();
    if(!resendKey||!from)throw new Error("email_provider_not_configured");
    const html=`<main style="font-family:Arial,sans-serif;color:#173d33;max-width:720px"><h1 style="font-size:24px">NOVO CONTATO — VIAGEM PERFEITA TURISMO</h1><h2 style="font-size:16px">DADOS DO INTERESSADO</h2><table>${row("Nome",lead.name)}${row("Telefone",lead.phone)}${row("E-mail",lead.email)}${row("Cidade/UF",[lead.city,lead.state].filter(Boolean).join("/"))}</table><h2 style="font-size:16px">INTERESSE</h2><table>${row("Tipo de solicitação",notification.event_type)}${row("Caravana",interest?.experience_name)}${row("Destinos",interest?.destination)}${row("Período",interest?.desired_period)}${row("Duração",interest?.duration)}${row("Quantidade de viajantes",interest?.travelers_count)}${row("Acomodação",interest?.accommodation)}${row("Cidade de embarque",interest?.departure_city)}${row("Forma de pagamento desejada",interest?.payment_preference)}${row("Interesse principal",interest?.main_interest)}${row("Observações",interest?.custom_notes)}</table><h2 style="font-size:16px">ORIGEM</h2><table>${row("Página",lead.landing_page)}${row("Origem",lead.source_detail||lead.source)}${row("Campanha",[lead.utm_source,lead.utm_medium,lead.utm_campaign].filter(Boolean).join(" / "))}${row("Data e horário",lead.created_at)}${row("ID do lead",lead.id)}</table><h2 style="font-size:16px">AÇÕES</h2>${appUrl?`<p><a href="${appUrl}/admin/leads/${lead.id}">Abrir lead no CRM</a></p>`:""}<p><a href="https://wa.me/${clean(lead.phone).replace(/\D/g,"")}">Abrir WhatsApp</a></p></main>`;
    const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${resendKey}`,"Content-Type":"application/json"},body:JSON.stringify({from,to:[recipient],subject:notification.subject,html})});if(!response.ok)throw new Error(`provider_${response.status}`);
    const now=new Date().toISOString();await admin.from("email_notifications").update({status:"enviado",sent_at:now,last_error:null,updated_at:now}).eq("id",notificationId);await admin.from("leads").update({email_notification_status:"enviado",email_notification_sent_at:now}).eq("id",lead.id);await admin.from("lead_activities").insert({lead_id:lead.id,activity_type:"email_sent",title:"Cópia do lead enviada por e-mail",metadata:{notification_id:notificationId}});
    return new Response(JSON.stringify({status:"enviado"}),{headers:{...cors,"Content-Type":"application/json"}});
  }catch(error){const message=error instanceof Error?error.message:"unknown_error";if(notificationId){const {data:n}=await admin.from("email_notifications").select("lead_id").eq("id",notificationId).maybeSingle();await admin.from("email_notifications").update({status:"falhou",last_error:message.slice(0,300),updated_at:new Date().toISOString()}).eq("id",notificationId);if(n?.lead_id){await admin.from("leads").update({email_notification_status:"falhou"}).eq("id",n.lead_id);await admin.from("lead_activities").insert({lead_id:n.lead_id,activity_type:"email_failed",title:"Falha no envio da cópia por e-mail",metadata:{notification_id:notificationId,error:message.slice(0,120)}})}}return new Response(JSON.stringify({status:"falhou"}),{status:202,headers:{...cors,"Content-Type":"application/json"}})}
});
