import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const clean=(value:unknown)=>typeof value==="string"?value.trim():value==null?"":String(value);
const escapeHtml=(value:unknown)=>clean(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]!));
const row=(label:string,value:unknown)=>clean(value)?`<tr><th style="padding:6px 12px 6px 0;text-align:left;vertical-align:top">${escapeHtml(label)}</th><td style="padding:6px 0">${escapeHtml(value)}</td></tr>`:"";

Deno.serve(async(request)=>{
  if(request.method==="OPTIONS")return new Response("ok",{headers:cors});
  const supabaseUrl=Deno.env.get("SUPABASE_URL");const serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");const resendKey=Deno.env.get("RESEND_API_KEY");
  const recipient=Deno.env.get("CRM_NOTIFICATION_EMAIL")||"viagemperfeitatrip@gmail.com";const from=Deno.env.get("CRM_FROM_EMAIL");const appUrl=(Deno.env.get("APP_URL")||"").replace(/\/$/,"");
  if(!supabaseUrl||!serviceKey)return new Response(JSON.stringify({status:"falhou"}),{status:500,headers:{...cors,"Content-Type":"application/json"}});
  const admin=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false}});let notificationId="";
  try{
    notificationId=clean((await request.json()).notificationId);if(!notificationId)throw new Error("notification_id_required");
    const {data:notification,error:queueError}=await admin.from("email_notifications").select("id,event_type,lead_id,reservation_id,proposal_id,recipient,subject,status,attempts,metadata").eq("id",notificationId).single();
    if(queueError||!notification)throw new Error("notification_not_found");if(notification.status==="enviado")return new Response(JSON.stringify({status:"enviado"}),{headers:{...cors,"Content-Type":"application/json"}});if(notification.attempts>=3)throw new Error("retry_limit_reached");
    const {data:claimed}=await admin.from("email_notifications").update({status:"processando",attempts:notification.attempts+1,updated_at:new Date().toISOString()}).eq("id",notificationId).in("status",["pendente","falhou"]).select("id").maybeSingle();if(!claimed)throw new Error("notification_already_processing");
    const {data:lead}=notification.lead_id?await admin.from("leads").select("id,name,phone,email,city,state,source,source_detail,utm_source,utm_medium,utm_campaign,landing_page,created_at").eq("id",notification.lead_id).maybeSingle():{data:null};
    const {data:interest}=lead?await admin.from("lead_interests").select("experience_name,destination,desired_period,duration,travelers_count,accommodation,departure_city,payment_preference,main_interest,custom_notes,created_at").eq("lead_id",lead.id).order("created_at",{ascending:false}).limit(1).maybeSingle():{data:null};
    const {data:reservation}=notification.reservation_id?await admin.from("reservations").select("id,reservation_code,customer_id,caravan_id,status,travelers_count,departure_city,final_value,payment_status,created_at").eq("id",notification.reservation_id).maybeSingle():{data:null};
    const {data:customer}=reservation?.customer_id?await admin.from("customers").select("id,name,phone,email,city,state").eq("id",reservation.customer_id).maybeSingle():{data:null};
    const {data:caravan}=reservation?.caravan_id?await admin.from("caravans").select("id,name,destination,start_date,end_date").eq("id",reservation.caravan_id).maybeSingle():{data:null};
    if(!lead&&!reservation&&!notification.proposal_id)throw new Error("notification_context_not_found");
    if(!resendKey||!from)throw new Error("email_provider_not_configured");
    const contact=lead||customer;const entityPath=lead?`leads/${lead.id}`:reservation?"reservas":"dashboard";
    const html=`<main style="font-family:Arial,sans-serif;color:#173d33;max-width:720px"><h1 style="font-size:24px">ATUALIZAÇÃO OPERACIONAL — VIAGEM PERFEITA TURISMO</h1><h2 style="font-size:16px">CONTATO</h2><table>${row("Nome",contact?.name)}${row("Telefone",contact?.phone)}${row("E-mail",contact?.email)}${row("Cidade/UF",[contact?.city,contact?.state].filter(Boolean).join("/"))}</table><h2 style="font-size:16px">EVENTO</h2><table>${row("Tipo",notification.event_type)}${row("Caravana",interest?.experience_name||caravan?.name)}${row("Destino",interest?.destination||caravan?.destination)}${row("Período",interest?.desired_period||[caravan?.start_date,caravan?.end_date].filter(Boolean).join(" a "))}${row("Código da reserva",reservation?.reservation_code)}${row("Situação da reserva",reservation?.status)}${row("Viajantes",interest?.travelers_count||reservation?.travelers_count)}${row("Cidade de embarque",interest?.departure_city||reservation?.departure_city)}${row("Valor final",reservation?.final_value)}${row("Pagamento",interest?.payment_preference||reservation?.payment_status)}${row("Interesse principal",interest?.main_interest)}${row("Observações",interest?.custom_notes)}${row("Detalhes",notification.metadata?JSON.stringify(notification.metadata):"")}</table>${lead?`<h2 style="font-size:16px">ORIGEM</h2><table>${row("Página",lead.landing_page)}${row("Origem",lead.source_detail||lead.source)}${row("Campanha",[lead.utm_source,lead.utm_medium,lead.utm_campaign].filter(Boolean).join(" / "))}${row("Data e horário",lead.created_at)}${row("ID do lead",lead.id)}</table>`:""}<h2 style="font-size:16px">AÇÕES</h2>${appUrl?`<p><a href="${appUrl}/admin/${entityPath}">Abrir no CRM</a></p>`:""}${contact?.phone?`<p><a href="https://wa.me/${clean(contact.phone).replace(/\D/g,"")}">Abrir WhatsApp</a></p>`:""}</main>`;
    const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${resendKey}`,"Content-Type":"application/json"},body:JSON.stringify({from,to:[notification.recipient||recipient],subject:notification.subject,html})});if(!response.ok)throw new Error(`provider_${response.status}`);
    const now=new Date().toISOString();await admin.from("email_notifications").update({status:"enviado",sent_at:now,last_error:null,updated_at:now}).eq("id",notificationId);if(lead){await admin.from("leads").update({email_notification_status:"enviado",email_notification_sent_at:now}).eq("id",lead.id);await admin.from("lead_activities").insert({lead_id:lead.id,activity_type:"email_sent",title:"Cópia do lead enviada por e-mail",metadata:{notification_id:notificationId}})}
    return new Response(JSON.stringify({status:"enviado"}),{headers:{...cors,"Content-Type":"application/json"}});
  }catch(error){const message=error instanceof Error?error.message:"unknown_error";if(notificationId){const {data:n}=await admin.from("email_notifications").select("lead_id").eq("id",notificationId).maybeSingle();await admin.from("email_notifications").update({status:"falhou",last_error:message.slice(0,300),updated_at:new Date().toISOString()}).eq("id",notificationId);if(n?.lead_id){await admin.from("leads").update({email_notification_status:"falhou"}).eq("id",n.lead_id);await admin.from("lead_activities").insert({lead_id:n.lead_id,activity_type:"email_failed",title:"Falha no envio da cópia por e-mail",metadata:{notification_id:notificationId,error:message.slice(0,120)}})}}return new Response(JSON.stringify({status:"falhou"}),{status:202,headers:{...cors,"Content-Type":"application/json"}})}
});
