import type { Metadata } from "next";
import { Banknote, CloudSun, Languages, MapPinned, MapPin, Sparkles } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHero } from "../../../components/page-hero";
import { PublicPage } from "../../../components/public-shell";
import { TripFaq } from "../../../components/trip-faq";
import { WhatsAppLink } from "../../../components/whatsapp-link";
import { destinations, getDestination } from "../../../lib/destinations";
export const dynamicParams=false;
export function generateStaticParams(){return destinations.map(({slug})=>({slug}))}
const facts:Record<string,{climate:string;currency:string;language:string;curiosity:string}>={
  israel:{climate:"Mediterrâneo, com variações entre litoral, montanhas e deserto.",currency:"Novo shekel israelense",language:"Hebraico e árabe; inglês é amplamente utilizado.",curiosity:"Em poucos quilômetros, paisagens e camadas históricas muito diferentes se encontram."},
  egito:{climate:"Predominantemente desértico, com dias secos e grande amplitude térmica.",currency:"Libra egípcia",language:"Árabe; inglês é comum no setor turístico.",curiosity:"O Nilo estruturou cidades, agricultura e rotas de uma civilização milenar."},
  jordania:{climate:"Árido, com variações importantes entre deserto e regiões elevadas.",currency:"Dinar jordaniano",language:"Árabe; inglês é utilizado em áreas turísticas.",curiosity:"Petra foi esculpida em rocha e integrou antigas rotas comerciais."},
  turquia:{climate:"Varia entre mediterrâneo, continental e regiões de altitude.",currency:"Lira turca",language:"Turco; inglês é encontrado nos principais centros turísticos.",curiosity:"Istambul conecta geograficamente Europa e Ásia."},
  grecia:{climate:"Mediterrâneo, com verões secos e invernos mais amenos no litoral.",currency:"Euro",language:"Grego; inglês é comum no turismo.",curiosity:"Cidades gregas aparecem tanto na história clássica quanto nas viagens do apóstolo Paulo."},
  italia:{climate:"Mediterrâneo em boa parte do país, com variação regional e sazonal.",currency:"Euro",language:"Italiano; inglês é comum em áreas turísticas.",curiosity:"Arte, arqueologia e tradição cristã convivem em cidades com séculos de história."},
  europa:{climate:"Varia amplamente conforme países, estações e altitude.",currency:"Euro em muitos destinos; alguns países mantêm moeda própria.",language:"Vários idiomas; o inglês é frequente em serviços turísticos.",curiosity:"Um roteiro pode conectar diferentes tradições, períodos históricos e paisagens."},
};
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const d=getDestination((await params).slug);if(!d)return{robots:{index:false}};return{title:`Viagem para ${d.name} | Viagem Perfeita Turismo`,description:d.introduction,alternates:{canonical:`/destinos/${d.slug}`},openGraph:{title:`Viagem para ${d.name}`,description:d.introduction,images:[d.image]}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const d=getDestination((await params).slug);if(!d)notFound();const f=facts[d.slug];return <PublicPage><PageHero eyebrow="Destino" title={d.name} description={d.introduction} image={d.image}/>
  <section className="section"><div className="shell destination-detail"><div><p className="eyebrow">Experiência histórica</p><h2>{d.headline}</h2><p>{d.history}</p><h3>Experiência espiritual</h3><p>{d.spirituality}</p><h3>Principais lugares</h3><ul>{d.places.map(p=><li key={p}><MapPin/>{p}</li>)}</ul></div><aside><h3>Planejamento responsável</h3><b>Melhor época</b><p>{d.bestPeriod}</p><b>Documentação</b><p>{d.documentation}</p><WhatsAppLink destination={d.name} tripName={`Experiência em ${d.name}`} buttonText="Planejar viagem">Planejar viagem</WhatsAppLink></aside></div></section>
  <section className="destination-facts-section section"><div className="shell"><p className="eyebrow light">Conheça antes de embarcar</p><div className="destination-facts"><div><CloudSun/><b>Clima</b><p>{f.climate}</p></div><div><Banknote/><b>Moeda</b><p>{f.currency}</p></div><div><Languages/><b>Idioma</b><p>{f.language}</p></div><div><Sparkles/><b>Curiosidade</b><p>{f.curiosity}</p></div></div></div></section>
  <section className="section"><div className="shell map-card"><div><MapPinned/><p className="eyebrow">Mapa do destino</p><h2>Entenda onde a experiência acontece.</h2><p>Consulte a localização geral. O mapa diário e os deslocamentos definitivos acompanham o roteiro oficial de cada caravana.</p></div><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(d.name)}`} target="_blank" rel="noopener noreferrer" aria-label={`Abrir ${d.name} no Google Maps`}>Abrir mapa de {d.name}</a></div></section>
  <section className="section destination-gallery"><div className="shell"><p className="eyebrow">Galeria de inspiração</p><h2 className="section-title">Paisagens que ajudam a imaginar a jornada.</h2><div className="editorial-gallery"><img src={d.image} alt={`Vista de ${d.name}`}/><div style={{backgroundImage:`linear-gradient(rgba(7,30,25,.15),rgba(7,30,25,.55)),url(${d.image})`}}><span>{d.places[0]}</span></div><div style={{backgroundImage:`linear-gradient(rgba(7,30,25,.15),rgba(7,30,25,.55)),url(${d.image})`}}><span>{d.places[1]||d.name}</span></div></div><p className="journey-authenticity">Imagens ilustrativas do destino. Registros reais da Viagem Perfeita são identificados na página de caravanas realizadas.</p></div></section>
  <section className="section related-experiences"><div className="shell"><p className="eyebrow">Caravanas disponíveis</p><h2 className="section-title">Encontre uma saída que inclui {d.name}.</h2><Link className="journey-all-link" href="/caravanas">Ver catálogo de caravanas</Link></div></section>
  <section className="section"><div className="shell faq-grid"><div><p className="eyebrow">FAQ de {d.name}</p><h2>Antes de planejar.</h2><Link className="text-link" href="/documentacao">Orientações de documentação</Link></div><TripFaq items={d.faqs}/></div></section></PublicPage>}
