import type { Metadata } from "next";
import { Check } from "lucide-react";
import { BasicContentPage } from "../../components/basic-content-page";
import { WhatsAppLink } from "../../components/whatsapp-link";
import { TripFaq } from "../../components/trip-faq";
export const metadata:Metadata={title:"Líderes de caravanas | Viagem Perfeita Turismo",description:"Planejamento de grupos para pastores, igrejas, líderes, ministérios e parceiros.",alternates:{canonical:"/lideres-de-caravanas"}};
const steps=["Entendimento do propósito e do perfil do grupo","Criação do roteiro e planejamento do período","Apoio de divulgação e captação de interessados","Reuniões preparatórias com os participantes","Organização comercial e operacional","Acompanhamento antes, durante e depois da jornada"];
const faqs:Array<[string,string]>=[["Preciso ter um grupo completo para começar?","Não. A conversa inicial ajuda a avaliar o perfil, a estimativa de participantes e o melhor caminho para estruturar a caravana."],["A equipe ajuda na divulgação?","O formato de apoio é definido na proposta de cada grupo e pode incluir materiais e orientação para comunicação e captação de interessados."],["O roteiro pode ser personalizado?","Sim. Destinos, período, ritmo e experiências são planejados conforme o propósito e o perfil do grupo."],["Como recebo valores e condições?","Após entender as necessidades do grupo, a equipe apresenta uma proposta oficial com escopo, condições e próximos passos."]];
export default function Page(){return <BasicContentPage eyebrow="Líderes e grupos" title="Transforme um propósito em uma jornada bem organizada." description="Atendimento próximo para pastores, igrejas, líderes, cantores, ministérios, grupos familiares, empresas e comunidades."><div className="leader-steps">{steps.map((s,i)=><div key={s}><span>{i+1}</span><p><Check/>{s}</p></div>)}</div><section><p className="eyebrow">Dúvidas de líderes</p><TripFaq items={faqs}/></section><section className="content-cta"><h2>Monte sua própria caravana.</h2><p>Conte o perfil do seu grupo, os destinos desejados e o período ideal. Nossa equipe prepara uma proposta personalizada, com condições apresentadas de forma clara.</p><WhatsAppLink tripName="Grupo liderado" initialInterest="Solicitar proposta para líderes" buttonText="Solicitar proposta">Solicitar proposta</WhatsAppLink></section></BasicContentPage>}
