alter table public.lead_interests add column if not exists duration text;

create or replace function public.upsert_public_lead(lead_payload jsonb) returns jsonb language plpgsql security definer set search_path=public as $$ declare target_id uuid;existing boolean:=false;begin
  if coalesce(trim(lead_payload->>'name'),'')='' or coalesce(trim(lead_payload->>'phone_normalized'),'')='' or coalesce((lead_payload->>'consent')::boolean,false)=false then raise exception 'invalid lead';end if;
  select id into target_id from public.leads where deleted_at is null and (phone_normalized=lead_payload->>'phone_normalized' or (nullif(lower(lead_payload->>'email'),'') is not null and lower(email)=lower(lead_payload->>'email'))) order by updated_at desc limit 1;
  if target_id is null then insert into public.leads(name,phone,phone_normalized,email,city,state,source,source_detail,utm_source,utm_medium,utm_campaign,utm_content,utm_term,landing_page,referrer,consent,consent_at) values(lead_payload->>'name',lead_payload->>'phone',lead_payload->>'phone_normalized',nullif(lead_payload->>'email',''),nullif(lead_payload->>'city',''),nullif(lead_payload->>'state',''),coalesce(lead_payload->>'source','Site'),lead_payload->>'source_detail',lead_payload->>'utm_source',lead_payload->>'utm_medium',lead_payload->>'utm_campaign',lead_payload->>'utm_content',lead_payload->>'utm_term',lead_payload->>'landing_page',lead_payload->>'referrer',true,coalesce((lead_payload->>'consent_at')::timestamptz,now())) returning id into target_id;
  else existing:=true;update public.leads set updated_at=now(),name=coalesce(nullif(lead_payload->>'name',''),name),phone=coalesce(nullif(lead_payload->>'phone',''),phone),email=coalesce(nullif(lead_payload->>'email',''),email),city=coalesce(nullif(lead_payload->>'city',''),city),state=coalesce(nullif(lead_payload->>'state',''),state) where id=target_id;end if;
  insert into public.lead_interests(lead_id,experience_name,destination,desired_period,duration,travelers_count,accommodation,departure_city,payment_preference,main_interest,custom_notes) values(target_id,lead_payload->>'experience_name',lead_payload->>'destination',lead_payload->>'desired_period',lead_payload->>'duration',nullif(lead_payload->>'travelers','')::integer,lead_payload->>'accommodation',lead_payload->>'departureCity',lead_payload->>'paymentPreference',lead_payload->>'interest',lead_payload->>'notes');
  insert into public.lead_activities(lead_id,activity_type,title,description,metadata) values(target_id,case when existing then 'new_interest' else 'lead_created' end,case when existing then 'Contato existente demonstrou novo interesse' else 'Lead criado pelo site' end,lead_payload->>'source_detail',jsonb_build_object('landing_page',lead_payload->>'landing_page','experience_name',lead_payload->>'experience_name','duration',lead_payload->>'duration'));
  return jsonb_build_object('lead_id',target_id,'duplicate',existing);
end $$;

grant execute on function public.upsert_public_lead(jsonb) to anon,authenticated;
