-- Conteúdo institucional editável. Aplicar depois de 202608030001_crm_base.sql.
create table if not exists public.destinations_content(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,data jsonb not null default '{}'::jsonb,published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table if not exists public.experiences_content(id uuid primary key default gen_random_uuid(),slug text unique not null,title text not null,data jsonb not null default '{}'::jsonb,status text not null default 'rascunho',published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table if not exists public.faqs_content(id uuid primary key default gen_random_uuid(),question text not null,answer text not null,scope text not null default 'geral',scope_id uuid,position integer not null default 0,published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table if not exists public.articles_content(id uuid primary key default gen_random_uuid(),slug text unique not null,title text not null,category text not null,excerpt text,content jsonb not null default '[]'::jsonb,seo jsonb not null default '{}'::jsonb,published boolean not null default false,published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table if not exists public.media_content(id uuid primary key default gen_random_uuid(),kind text not null check(kind in ('imagem','video')),title text not null,alt_text text,file_path text,external_url text,poster_path text,metadata jsonb not null default '{}'::jsonb,published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table if not exists public.testimonials_content(id uuid primary key default gen_random_uuid(),author_name text not null,quote text not null,context text,source_url text,media_id uuid references public.media_content(id),published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table if not exists public.leaders_content(id uuid primary key default gen_random_uuid(),name text not null,role text,bio text,photo_media_id uuid references public.media_content(id),published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);
create table if not exists public.partners_content(id uuid primary key default gen_random_uuid(),name text not null,description text,website text,logo_media_id uuid references public.media_content(id),published boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz);

create index if not exists destinations_content_published_idx on public.destinations_content(published,updated_at desc);
create index if not exists experiences_content_published_idx on public.experiences_content(published,status,updated_at desc);
create index if not exists articles_content_category_idx on public.articles_content(category,published,published_at desc);
create index if not exists media_content_kind_idx on public.media_content(kind,published,created_at desc);

alter table public.destinations_content enable row level security;alter table public.experiences_content enable row level security;alter table public.faqs_content enable row level security;alter table public.articles_content enable row level security;alter table public.media_content enable row level security;alter table public.testimonials_content enable row level security;alter table public.leaders_content enable row level security;alter table public.partners_content enable row level security;

do $$ declare table_name text; begin foreach table_name in array array['destinations_content','experiences_content','faqs_content','articles_content','media_content','testimonials_content','leaders_content','partners_content'] loop
  execute format('create policy %I on public.%I for select using (published = true or public.current_role() in (''administrador'',''gestor'',''consultor'',''visualizador''))','read_'||table_name,table_name);
  execute format('create policy %I on public.%I for all using (public.current_role() in (''administrador'',''gestor'')) with check (public.current_role() in (''administrador'',''gestor''))','manage_'||table_name,table_name);
end loop; end $$;

insert into storage.buckets(id,name,public) values('site-media','site-media',true) on conflict(id) do nothing;
create policy public_site_media_read on storage.objects for select using(bucket_id='site-media');
create policy managers_site_media_write on storage.objects for insert to authenticated with check(bucket_id='site-media' and public.current_role() in ('administrador','gestor'));
create policy managers_site_media_update on storage.objects for update to authenticated using(bucket_id='site-media' and public.current_role() in ('administrador','gestor'));
create policy managers_site_media_delete on storage.objects for delete to authenticated using(bucket_id='site-media' and public.current_role() in ('administrador','gestor'));
