create extension if not exists pgcrypto;
create type public.user_role as enum ('administrador','gestor','consultor','visualizador');
create type public.lead_temperature as enum ('frio','morno','quente','prioridade');
create type public.lead_status as enum ('novo_lead','primeiro_contato','em_atendimento','roteiro_enviado','proposta_enviada','aguardando_resposta','negociacao','reserva_iniciada','aguardando_pagamento','reserva_confirmada','documentacao_pendente','passageiro_confirmado','perdido','arquivado');

create table public.profiles(id uuid primary key references auth.users(id) on delete restrict,full_name text not null,email text not null,phone text,avatar_url text,role public.user_role not null default 'visualizador',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.caravans(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,destination text not null,departure_date date,return_date date,status_public text,status_internal text not null default 'rascunho',published boolean not null default false,capacity integer check(capacity>=0),available_spots integer check(available_spots>=0),archived_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.leads(id uuid primary key default gen_random_uuid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),name text not null,phone text not null,phone_normalized text not null,email text,city text,state text,country text default 'Brasil',source text not null default 'Site',source_detail text,utm_source text,utm_medium text,utm_campaign text,utm_content text,utm_term text,landing_page text,referrer text,status public.lead_status not null default 'novo_lead',temperature public.lead_temperature not null default 'morno',assigned_to uuid references public.profiles(id) on delete set null,next_action_at timestamptz,last_contact_at timestamptz,lost_reason text,notes_summary text,consent boolean not null default false,consent_at timestamptz,whatsapp_started boolean not null default false,converted_customer_id uuid,archived_at timestamptz,deleted_at timestamptz);
create table public.lead_interests(id uuid primary key default gen_random_uuid(),lead_id uuid not null references public.leads(id) on delete cascade,caravan_id uuid references public.caravans(id) on delete set null,experience_name text,destination text,desired_period text,travelers_count integer,accommodation text,departure_city text,payment_preference text,main_interest text,custom_notes text,created_at timestamptz not null default now());
create table public.lead_notes(id uuid primary key default gen_random_uuid(),lead_id uuid not null references public.leads(id) on delete cascade,author_id uuid not null references public.profiles(id) on delete restrict,content text not null,is_private boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.lead_activities(id uuid primary key default gen_random_uuid(),lead_id uuid not null references public.leads(id) on delete cascade,user_id uuid references public.profiles(id) on delete set null,activity_type text not null,title text not null,description text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table public.tasks(id uuid primary key default gen_random_uuid(),lead_id uuid references public.leads(id) on delete cascade,assigned_to uuid references public.profiles(id) on delete set null,created_by uuid references public.profiles(id) on delete set null,title text not null,description text,due_at timestamptz,priority text not null default 'media',status text not null default 'pendente',completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.customers(id uuid primary key default gen_random_uuid(),lead_id uuid unique references public.leads(id) on delete set null,name text not null,phone text,email text,city text,state text,birth_date date,status text not null default 'ativo',archived_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.leads add constraint leads_converted_customer_fk foreign key(converted_customer_id) references public.customers(id) on delete set null;
create table public.reservations(id uuid primary key default gen_random_uuid(),customer_id uuid not null references public.customers(id) on delete restrict,caravan_id uuid references public.caravans(id) on delete set null,lead_id uuid references public.leads(id) on delete set null,reservation_code text unique,status text not null default 'pre_reserva',travelers_count integer not null default 1,accommodation text,departure_city text,total_value numeric(14,2),currency text not null default 'BRL',discount numeric(14,2) not null default 0,final_value numeric(14,2),payment_status text not null default 'pendente',reserved_at timestamptz not null default now(),confirmed_at timestamptz,cancelled_at timestamptz,created_by uuid references public.profiles(id) on delete set null,archived_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.reservation_travelers(id uuid primary key default gen_random_uuid(),reservation_id uuid not null references public.reservations(id) on delete cascade,full_name text not null,traveler_type text not null default 'adulto',document_status text not null default 'nao_solicitado',passport_status text not null default 'nao_solicitado',visa_status text not null default 'nao_solicitado',notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.payments(id uuid primary key default gen_random_uuid(),reservation_id uuid not null references public.reservations(id) on delete cascade,description text not null,amount numeric(14,2) not null,due_date date,paid_at timestamptz,status text not null default 'pendente',payment_method text,installment_number integer,external_reference text,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.documents(id uuid primary key default gen_random_uuid(),reservation_id uuid not null references public.reservations(id) on delete cascade,traveler_id uuid references public.reservation_travelers(id) on delete cascade,document_type text not null,status text not null default 'nao_solicitado',file_path text,expires_at date,notes text,uploaded_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.tags(id uuid primary key default gen_random_uuid(),name text not null unique,color text not null default '#769286',created_at timestamptz not null default now());
create table public.lead_tags(lead_id uuid not null references public.leads(id) on delete cascade,tag_id uuid not null references public.tags(id) on delete cascade,primary key(lead_id,tag_id));
create table public.system_settings(id uuid primary key default gen_random_uuid(),key text not null unique,value jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now(),updated_by uuid references public.profiles(id) on delete set null);
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,type text not null,title text not null,body text,read_at timestamptz,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table public.audit_logs(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete set null,action text not null,entity_type text not null,entity_id uuid,before_data jsonb,after_data jsonb,ip_reference text,created_at timestamptz not null default now());

create index leads_phone_idx on public.leads(phone_normalized);create index leads_email_idx on public.leads(lower(email));create index leads_status_idx on public.leads(status);create index leads_assigned_idx on public.leads(assigned_to);create index leads_created_idx on public.leads(created_at desc);create index leads_next_action_idx on public.leads(next_action_at);create index interests_caravan_idx on public.lead_interests(caravan_id);create index tasks_due_idx on public.tasks(due_at,status);

create or replace function public.current_role() returns public.user_role language sql stable security definer set search_path=public as $$ select role from public.profiles where id=auth.uid() and active=true $$;
create or replace function public.can_manage_all() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(public.current_role() in ('administrador','gestor'),false) $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,email,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1)),new.email,'visualizador') on conflict(id) do nothing;return new;end $$;
create trigger auth_user_profile after insert on auth.users for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;alter table public.caravans enable row level security;alter table public.leads enable row level security;alter table public.lead_interests enable row level security;alter table public.lead_notes enable row level security;alter table public.lead_activities enable row level security;alter table public.tasks enable row level security;alter table public.customers enable row level security;alter table public.reservations enable row level security;alter table public.reservation_travelers enable row level security;alter table public.payments enable row level security;alter table public.documents enable row level security;alter table public.tags enable row level security;alter table public.lead_tags enable row level security;alter table public.system_settings enable row level security;alter table public.notifications enable row level security;alter table public.audit_logs enable row level security;

create policy profiles_self_read on public.profiles for select using(id=auth.uid() or public.can_manage_all());
create policy managers_profiles_write on public.profiles for update using(public.current_role()='administrador') with check(public.current_role()='administrador');
create policy public_caravans_read on public.caravans for select using(published=true or public.current_role() in ('administrador','gestor','consultor','visualizador'));
create policy managers_caravans_write on public.caravans for all using(public.current_role() in ('administrador','gestor')) with check(public.current_role() in ('administrador','gestor'));
create policy staff_leads_read on public.leads for select using(public.can_manage_all() or (public.current_role()='consultor' and assigned_to=auth.uid()) or (public.current_role()='visualizador' and assigned_to=auth.uid()));
create policy staff_leads_write on public.leads for update using(public.can_manage_all() or (public.current_role()='consultor' and assigned_to=auth.uid())) with check(public.can_manage_all() or (public.current_role()='consultor' and assigned_to=auth.uid()));
create policy related_interests on public.lead_interests for select using(exists(select 1 from public.leads l where l.id=lead_id and (public.can_manage_all() or l.assigned_to=auth.uid())));
create policy related_notes on public.lead_notes for all using(exists(select 1 from public.leads l where l.id=lead_id and (public.can_manage_all() or l.assigned_to=auth.uid()))) with check(exists(select 1 from public.leads l where l.id=lead_id and (public.can_manage_all() or l.assigned_to=auth.uid())));
create policy related_activities on public.lead_activities for all using(exists(select 1 from public.leads l where l.id=lead_id and (public.can_manage_all() or l.assigned_to=auth.uid()))) with check(exists(select 1 from public.leads l where l.id=lead_id and (public.can_manage_all() or l.assigned_to=auth.uid())));
create policy related_tasks on public.tasks for all using(public.can_manage_all() or assigned_to=auth.uid()) with check(public.can_manage_all() or assigned_to=auth.uid());
create policy staff_customers on public.customers for all using(public.can_manage_all() or exists(select 1 from public.leads l where l.id=lead_id and l.assigned_to=auth.uid())) with check(public.can_manage_all() or exists(select 1 from public.leads l where l.id=lead_id and l.assigned_to=auth.uid()));
create policy staff_reservations on public.reservations for all using(public.can_manage_all() or exists(select 1 from public.leads l where l.id=lead_id and l.assigned_to=auth.uid())) with check(public.can_manage_all() or exists(select 1 from public.leads l where l.id=lead_id and l.assigned_to=auth.uid()));
create policy staff_travelers on public.reservation_travelers for all using(exists(select 1 from public.reservations r join public.leads l on l.id=r.lead_id where r.id=reservation_id and (public.can_manage_all() or l.assigned_to=auth.uid()))) with check(exists(select 1 from public.reservations r join public.leads l on l.id=r.lead_id where r.id=reservation_id and (public.can_manage_all() or l.assigned_to=auth.uid())));
create policy staff_payments on public.payments for all using(exists(select 1 from public.reservations r join public.leads l on l.id=r.lead_id where r.id=reservation_id and (public.can_manage_all() or l.assigned_to=auth.uid()))) with check(exists(select 1 from public.reservations r join public.leads l on l.id=r.lead_id where r.id=reservation_id and (public.can_manage_all() or l.assigned_to=auth.uid())));
create policy staff_documents on public.documents for all using(exists(select 1 from public.reservations r join public.leads l on l.id=r.lead_id where r.id=reservation_id and (public.can_manage_all() or l.assigned_to=auth.uid()))) with check(exists(select 1 from public.reservations r join public.leads l on l.id=r.lead_id where r.id=reservation_id and (public.can_manage_all() or l.assigned_to=auth.uid())));
create policy staff_tags on public.tags for select using(auth.uid() is not null);create policy managers_tags_write on public.tags for all using(public.can_manage_all()) with check(public.can_manage_all());
create policy staff_lead_tags on public.lead_tags for all using(auth.uid() is not null) with check(auth.uid() is not null);
create policy admins_settings on public.system_settings for all using(public.current_role()='administrador') with check(public.current_role()='administrador');
create policy notifications_own on public.notifications for select using(user_id=auth.uid());create policy notifications_update on public.notifications for update using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy managers_audit on public.audit_logs for select using(public.current_role() in ('administrador','gestor'));

create or replace function public.upsert_public_lead(lead_payload jsonb) returns jsonb language plpgsql security definer set search_path=public as $$ declare target_id uuid;existing boolean:=false;begin
  if coalesce(trim(lead_payload->>'name'),'')='' or coalesce(trim(lead_payload->>'phone_normalized'),'')='' or coalesce((lead_payload->>'consent')::boolean,false)=false then raise exception 'invalid lead';end if;
  select id into target_id from public.leads where deleted_at is null and (phone_normalized=lead_payload->>'phone_normalized' or (nullif(lower(lead_payload->>'email'),'') is not null and lower(email)=lower(lead_payload->>'email'))) order by updated_at desc limit 1;
  if target_id is null then insert into public.leads(name,phone,phone_normalized,email,city,state,source,source_detail,utm_source,utm_medium,utm_campaign,utm_content,utm_term,landing_page,referrer,consent,consent_at) values(lead_payload->>'name',lead_payload->>'phone',lead_payload->>'phone_normalized',nullif(lead_payload->>'email',''),nullif(lead_payload->>'city',''),nullif(lead_payload->>'state',''),coalesce(lead_payload->>'source','Site'),lead_payload->>'source_detail',lead_payload->>'utm_source',lead_payload->>'utm_medium',lead_payload->>'utm_campaign',lead_payload->>'utm_content',lead_payload->>'utm_term',lead_payload->>'landing_page',lead_payload->>'referrer',true,coalesce((lead_payload->>'consent_at')::timestamptz,now())) returning id into target_id;
  else existing:=true;update public.leads set updated_at=now(),name=coalesce(nullif(lead_payload->>'name',''),name),email=coalesce(nullif(lead_payload->>'email',''),email),city=coalesce(nullif(lead_payload->>'city',''),city),state=coalesce(nullif(lead_payload->>'state',''),state) where id=target_id;end if;
  insert into public.lead_interests(lead_id,experience_name,destination,desired_period,travelers_count,accommodation,departure_city,payment_preference,main_interest,custom_notes) values(target_id,lead_payload->>'experience_name',lead_payload->>'destination',lead_payload->>'desired_period',nullif(lead_payload->>'travelers','')::integer,lead_payload->>'accommodation',lead_payload->>'departureCity',lead_payload->>'paymentPreference',lead_payload->>'interest',lead_payload->>'notes');
  insert into public.lead_activities(lead_id,activity_type,title,description,metadata) values(target_id,case when existing then 'new_interest' else 'lead_created' end,case when existing then 'Contato existente demonstrou novo interesse' else 'Lead criado pelo site' end,lead_payload->>'source_detail',jsonb_build_object('landing_page',lead_payload->>'landing_page'));
  return jsonb_build_object('lead_id',target_id,'duplicate',existing);
end $$;
grant execute on function public.upsert_public_lead(jsonb) to anon,authenticated;

create or replace function public.anonymize_lead(target_id uuid) returns void language plpgsql security definer set search_path=public as $$ declare before_row jsonb;begin if public.current_role() is distinct from 'administrador'::public.user_role then raise exception 'not authorized';end if;select to_jsonb(l) into before_row from public.leads l where id=target_id;update public.leads set name='Contato anonimizado',phone='',phone_normalized='anon-'||id::text,email=null,city=null,state=null,notes_summary=null,deleted_at=now(),updated_at=now() where id=target_id;insert into public.audit_logs(user_id,action,entity_type,entity_id,before_data,after_data) values(auth.uid(),'anonymize','lead',target_id,before_row,jsonb_build_object('anonymized',true));end $$;
grant execute on function public.anonymize_lead(uuid) to authenticated;

insert into storage.buckets(id,name,public) values('private-documents','private-documents',false) on conflict(id) do nothing;
create policy staff_private_documents_read on storage.objects for select to authenticated using(bucket_id='private-documents' and public.current_role() in ('administrador','gestor','consultor'));
create policy staff_private_documents_insert on storage.objects for insert to authenticated with check(bucket_id='private-documents' and public.current_role() in ('administrador','gestor','consultor'));
create policy managers_private_documents_delete on storage.objects for delete to authenticated using(bucket_id='private-documents' and public.current_role() in ('administrador','gestor'));
