-- Catálogo contínuo e administrável de caravanas.
alter table public.caravans add column if not exists subtitle text;
alter table public.caravans add column if not exists short_description text;
alter table public.caravans add column if not exists full_description text;
alter table public.caravans add column if not exists cover_image text;
alter table public.caravans add column if not exists month integer check(month between 1 and 12);
alter table public.caravans add column if not exists year integer check(year between 2020 and 2200);
alter table public.caravans add column if not exists duration_days integer check(duration_days>0);
alter table public.caravans add column if not exists duration_nights integer check(duration_nights>=0);
alter table public.caravans add column if not exists departure_city text;
alter table public.caravans add column if not exists countries text[] not null default '{}';
alter table public.caravans add column if not exists cities text[] not null default '{}';
alter table public.caravans add column if not exists category text not null default 'religioso';
alter table public.caravans add column if not exists priority integer not null default 100;
alter table public.caravans add column if not exists airline text;
alter table public.caravans add column if not exists hotel_category text;
alter table public.caravans add column if not exists meals text;
alter table public.caravans add column if not exists guide text;
alter table public.caravans add column if not exists coordinator text;
alter table public.caravans add column if not exists included jsonb not null default '[]'::jsonb;
alter table public.caravans add column if not exists not_included jsonb not null default '[]'::jsonb;
alter table public.caravans add column if not exists gallery jsonb not null default '[]'::jsonb;
alter table public.caravans add column if not exists price numeric(14,2);
alter table public.caravans add column if not exists currency text;
alter table public.caravans add column if not exists deposit numeric(14,2);
alter table public.caravans add column if not exists installments text;
alter table public.caravans add column if not exists cash_discount text;
alter table public.caravans add column if not exists condition_valid_until date;
alter table public.caravans add column if not exists commercial_notes text;
alter table public.caravans alter column status_internal set default 'confirmada';
create table if not exists public.caravan_itinerary_days(id uuid primary key default gen_random_uuid(),caravan_id uuid not null references public.caravans(id) on delete cascade,day_number integer not null,date date,city text,title text not null,description text,visits text[],meals text[],hotel text,transportation text,notes text,position integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(caravan_id,day_number));
create index if not exists caravans_calendar_idx on public.caravans(priority,year,month,departure_date);
create index if not exists caravan_itinerary_order_idx on public.caravan_itinerary_days(caravan_id,position,day_number);
alter table public.caravan_itinerary_days enable row level security;
create policy public_published_itinerary on public.caravan_itinerary_days for select using(exists(select 1 from public.caravans c where c.id=caravan_id and c.published=true));
create policy staff_manage_itinerary on public.caravan_itinerary_days for all to authenticated using(public.current_role() in ('administrador','gestor')) with check(public.current_role() in ('administrador','gestor'));
update public.caravans set status_internal='confirmada',status_public='disponivel',published=true where archived_at is null;
